import React, { useMemo, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useLocation, useRoute } from "wouter";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import {
  useCanViewFinancials,
  useCanViewSales,
} from "@/hooks/usePermissions";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import ShoppingList from "@/components/shopping/ShoppingList";

import {
  CalendarCheck,
  Users,
  MapPin,
  Phone,
  Mail,
  ChefHat,
  UtensilsCrossed,
  AlertTriangle,
  Loader2,
  Clock,
  ExternalLink,
  Wine,
  Package,
  ClipboardCheck,
  Timer,
  UserCheck,
  FileText,
  StickyNote,
  CalendarX,
  Share2,
  Copy,
  Link as LinkIcon,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

interface EventRow {
  id: number;
  clientId: number;
  estimateId: number | null;
  eventDate: string;
  startTime: string;
  endTime: string;
  eventType: string;
  guestCount: number;
  venue: string;
  menuId: number | null;
  status: "confirmed" | "in-progress" | "completed" | "cancelled";
  notes: string | null;
  completedTasks: string[] | null;
  createdAt: string;
  updatedAt: string;
}

interface ClientRow {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string | null;
  company: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  type: "prospect" | "customer";
}

interface EstimateRow {
  id: number;
  clientId: number;
  eventType: string;
  eventDate: string | null;
  guestCount: number | null;
  venue: string | null;
  venueAddress: string | null;
  venueCity: string | null;
  venueZip: string | null;
  items: unknown;
  subtotal: number;
  tax: number;
  total: number;
  status: string;
  notes: string | null;
}

interface QuoteRequestRow {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string | null;
  eventType: string;
  eventDate: string | null;
  eventStartTime: string | null;
  eventEndTime: string | null;
  guestCount: number;
  venueName: string | null;
  venueHasKitchen: boolean | null;
  serviceType: string | null;
  serviceStyle: string | null;
  menuTheme: string | null;
  menuTier: string | null;
  hasCocktailHour: boolean | null;
  cocktailStartTime: string | null;
  cocktailEndTime: string | null;
  mainMealStartTime: string | null;
  mainMealEndTime: string | null;
  menuSelections: Array<{ name: string; category: string; upcharge?: number }> | null;
  appetizers: {
    serviceStyle?: string;
    selections: Array<{ category: string; itemName: string; quantity: number; pricePerPiece?: number }>;
  } | null;
  desserts: Array<{ itemName: string; quantity: number; pricePerPiece?: number }> | null;
  beverages: {
    hasNonAlcoholic: boolean;
    hasAlcoholic: boolean;
    bartendingType?: string;
    liquorQuality?: string;
  } | null;
  equipment: {
    items: Array<{ item: string; quantity: number; pricePerUnit?: number }>;
    otherNotes?: string;
  } | null;
  dietary: {
    restrictions?: string[];
    allergies?: string[];
    specialNotes?: string;
  } | null;
  specialRequests: string | null;
  aiAnalysis: {
    eventComplexityScore?: number;
    estimatedPrepHours?: number;
    recommendedStaffCount?: number;
    pricingConfidence?: number;
    marginEstimate?: number;
    autoGeneratedNotes?: string;
  } | null;
}

interface MenuRow {
  id: number;
  name: string;
  themeKey: string | null;
  packages: Array<{
    tierKey: string;
    tierName: string;
    pricePerPersonCents: number;
    description?: string;
    selectionLimits?: Record<string, number>;
  }> | null;
}

interface FullEventPayload {
  event: EventRow;
  client: ClientRow | null;
  estimate: EstimateRow | null;
  quoteRequest: QuoteRequestRow | null;
  menu: MenuRow | null;
}

// ─── Checklist definition (hardcoded for v1) ────────────────────────────────

type ChecklistItem = { id: string; label: string };
type ChecklistStage = { key: string; title: string; description: string; items: ChecklistItem[] };

const CHECKLIST: ChecklistStage[] = [
  {
    key: "confirmed",
    title: "Confirmed",
    description: "Lock in the details as soon as the deposit clears.",
    items: [
      { id: "confirm_final_headcount", label: "Confirm final headcount with client" },
      { id: "invoice_sent", label: "Final invoice sent" },
      { id: "deposit_received", label: "Deposit received" },
      { id: "staff_assigned", label: "Staff assigned" },
      { id: "menu_finalized", label: "Menu finalized with client" },
      { id: "rentals_reserved", label: "Rentals reserved" },
      { id: "dietary_notes_confirmed", label: "Allergies/dietary restrictions confirmed" },
    ],
  },
  {
    key: "48h_out",
    title: "48 Hours Out",
    description: "Prep week — shop, pack, brief.",
    items: [
      { id: "shopping_done", label: "Shopping done" },
      { id: "rentals_picked_up", label: "Rentals picked up" },
      { id: "prep_started", label: "Prep started" },
      { id: "truck_loaded", label: "Truck loaded" },
      { id: "timeline_confirmed", label: "Timeline confirmed with venue" },
      { id: "final_count_locked", label: "Final headcount locked in for portioning" },
    ],
  },
  {
    key: "day_of",
    title: "Day Of",
    description: "Execution.",
    items: [
      { id: "team_briefed", label: "Team briefed" },
      { id: "arrived_onsite", label: "Arrived onsite" },
      { id: "setup_complete", label: "Setup complete" },
      { id: "service_started", label: "Service started" },
      { id: "service_complete", label: "Service complete" },
      { id: "breakdown_complete", label: "Breakdown complete" },
    ],
  },
  {
    key: "post_event",
    title: "Post-Event",
    description: "Wrap up and learn.",
    items: [
      { id: "rentals_returned", label: "Rentals returned" },
      { id: "final_invoice_paid", label: "Final invoice paid" },
      { id: "thank_you_sent", label: "Thank-you note sent" },
      { id: "post_event_notes", label: "Post-event notes captured" },
      { id: "photos_saved", label: "Event photos saved" },
    ],
  },
];

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatDate(iso: string | null): string {
  if (!iso) return "--";
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatTime(iso: string | null): string {
  if (!iso) return "";
  return new Date(iso).toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });
}

function daysUntil(iso: string): number {
  const now = new Date();
  const then = new Date(iso);
  now.setHours(0, 0, 0, 0);
  then.setHours(0, 0, 0, 0);
  return Math.round((then.getTime() - now.getTime()) / 86400000);
}

function countdownLabel(days: number): string {
  if (days < 0) return `${Math.abs(days)}d ago`;
  if (days === 0) return "Today";
  if (days === 1) return "Tomorrow";
  if (days < 7) return `In ${days}d`;
  if (days < 30) return `In ${Math.ceil(days / 7)}w`;
  return `In ${Math.ceil(days / 30)}mo`;
}

function urgencyBorder(days: number, status: string): string {
  if (status === "completed") return "border-gray-200";
  if (status === "cancelled") return "border-gray-200 opacity-60";
  if (days < 0) return "border-gray-300";
  if (days <= 2) return "border-red-300 bg-red-50/30";
  if (days <= 7) return "border-yellow-300 bg-yellow-50/30";
  return "border-green-200 bg-green-50/20";
}

const STATUS_COLORS: Record<string, string> = {
  confirmed: "bg-green-100 text-green-700 border-green-300",
  "in-progress": "bg-blue-100 text-blue-700 border-blue-300",
  completed: "bg-gray-100 text-gray-700 border-gray-300",
  cancelled: "bg-red-100 text-red-700 border-red-300",
};

function formatCents(cents: number | null | undefined): string {
  if (cents == null) return "--";
  return `$${(cents / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function titleCase(s: string | null | undefined): string {
  if (!s) return "";
  return s
    .split(/[_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

// ─── Main component ────────────────────────────────────────────────────────

export default function Events() {
  const [, navigate] = useLocation();
  const [matchDetail, params] = useRoute("/events/:id");
  const urlEventId = matchDetail && params?.id ? parseInt(params.id, 10) : null;
  const [selectedId, setSelectedId] = useState<number | null>(urlEventId);
  const [activeTab, setActiveTab] = useState<string>("upcoming");

  // Keep selectedId in sync with url
  React.useEffect(() => {
    if (urlEventId && urlEventId !== selectedId) {
      setSelectedId(urlEventId);
    }
  }, [urlEventId]); // eslint-disable-line react-hooks/exhaustive-deps

  const { data: events = [], isLoading: isLoadingEvents } = useQuery<EventRow[]>({
    queryKey: ["/api/events"],
  });

  const filteredEvents = useMemo(() => {
    const sorted = [...events].sort(
      (a, b) => new Date(a.eventDate).getTime() - new Date(b.eventDate).getTime()
    );

    if (activeTab === "all") return sorted;

    const now = new Date();
    now.setHours(0, 0, 0, 0);

    if (activeTab === "today") {
      return sorted.filter((e) => daysUntil(e.eventDate) === 0);
    }
    if (activeTab === "this_week") {
      return sorted.filter((e) => {
        const d = daysUntil(e.eventDate);
        return d >= 0 && d <= 7;
      });
    }
    if (activeTab === "past") {
      return sorted
        .filter((e) => daysUntil(e.eventDate) < 0)
        .reverse();
    }
    // upcoming (default)
    return sorted.filter((e) => daysUntil(e.eventDate) >= 0 && e.status !== "cancelled");
  }, [events, activeTab]);

  const handleSelectEvent = (id: number) => {
    setSelectedId(id);
    navigate(`/events/${id}`);
  };

  return (
    <div className="h-full">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <CalendarCheck className="h-7 w-7 text-primary" />
            Events
          </h1>
          <p className="text-muted-foreground mt-1">
            Every booked event, everything Mike needs to run it.
          </p>
        </div>
        <Badge variant="outline" className="text-sm py-1 px-3">
          {events.length} total event{events.length !== 1 ? "s" : ""}
        </Badge>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 min-h-[calc(100vh-12rem)]">
        {/* ─── Left Panel: Event List ──────────────────────────────────── */}
        <div className="w-full lg:w-[38%] flex flex-col">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="mb-4 flex-wrap">
              <TabsTrigger value="upcoming">Upcoming</TabsTrigger>
              <TabsTrigger value="today">Today</TabsTrigger>
              <TabsTrigger value="this_week">This Week</TabsTrigger>
              <TabsTrigger value="past">Past</TabsTrigger>
              <TabsTrigger value="all">All</TabsTrigger>
            </TabsList>

            <div className="space-y-3 overflow-y-auto max-h-[calc(100vh-16rem)] pr-1">
              {isLoadingEvents && (
                <div className="flex items-center justify-center py-16">
                  <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                </div>
              )}

              {!isLoadingEvents && filteredEvents.length === 0 && (
                <Card>
                  <CardContent className="py-12 text-center text-muted-foreground">
                    <CalendarX className="h-12 w-12 mx-auto mb-3 opacity-40" />
                    <p className="text-lg font-medium">No events</p>
                    <p className="text-sm mt-1">
                      Events appear here automatically when an estimate is accepted.
                    </p>
                  </CardContent>
                </Card>
              )}

              {filteredEvents.map((ev) => {
                const days = daysUntil(ev.eventDate);
                return (
                  <Card
                    key={ev.id}
                    className={`cursor-pointer transition-all hover:shadow-md border ${urgencyBorder(
                      days,
                      ev.status
                    )} ${selectedId === ev.id ? "ring-2 ring-primary shadow-md" : ""}`}
                    onClick={() => handleSelectEvent(ev.id)}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-semibold text-base truncate">
                              {ev.eventType}
                            </span>
                            <Badge
                              className={`${STATUS_COLORS[ev.status] ?? ""} border text-xs`}
                            >
                              {titleCase(ev.status)}
                            </Badge>
                          </div>
                          <div className="mt-1 text-sm text-muted-foreground flex flex-wrap items-center gap-x-3 gap-y-1">
                            <span className="flex items-center gap-1">
                              <CalendarCheck className="h-3.5 w-3.5" />
                              {formatDate(ev.eventDate)}
                            </span>
                            <span className="flex items-center gap-1">
                              <Clock className="h-3.5 w-3.5" />
                              {formatTime(ev.startTime)}
                            </span>
                            <span className="flex items-center gap-1">
                              <Users className="h-3.5 w-3.5" />
                              {ev.guestCount}
                            </span>
                          </div>
                          <div className="mt-1 text-xs text-muted-foreground flex items-center gap-1 truncate">
                            <MapPin className="h-3 w-3 shrink-0" />
                            <span className="truncate">{ev.venue}</span>
                          </div>
                        </div>
                        <div className="shrink-0 text-right">
                          <div
                            className={`text-sm font-semibold ${
                              days < 0
                                ? "text-gray-400"
                                : days <= 2
                                ? "text-red-600"
                                : days <= 7
                                ? "text-yellow-700"
                                : "text-green-700"
                            }`}
                          >
                            {countdownLabel(days)}
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </Tabs>
        </div>

        {/* ─── Right Panel: Event Detail ────────────────────────────────── */}
        <div className="w-full lg:w-[62%] overflow-y-auto max-h-[calc(100vh-12rem)]">
          {selectedId == null ? (
            <EmptyState />
          ) : (
            <EventDetail eventId={selectedId} />
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Empty state ────────────────────────────────────────────────────────────

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center h-full text-center py-24">
      <CalendarCheck className="h-16 w-16 text-muted-foreground/30 mb-4" />
      <p className="text-lg font-medium text-muted-foreground">
        Select an event to see everything Mike needs
      </p>
      <p className="text-sm text-muted-foreground/70 mt-1">
        Menu, dietary, shopping list, prep schedule, equipment, checklist — all in one place.
      </p>
    </div>
  );
}

// ─── Detail container (fetches full payload) ───────────────────────────────

function EventDetail({ eventId }: { eventId: number }) {
  const { data, isLoading, isError } = useQuery<FullEventPayload>({
    queryKey: [`/api/events/${eventId}/full`],
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-24">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (isError || !data) {
    return (
      <Card className="border-red-200 bg-red-50">
        <CardContent className="py-8 text-center text-red-600">
          <AlertTriangle className="h-8 w-8 mx-auto mb-2" />
          <p>Failed to load event details. Please refresh the page.</p>
        </CardContent>
      </Card>
    );
  }

  const { event, client, estimate, quoteRequest, menu } = data;

  return (
    <div className="space-y-4 pb-8">
      <EventHeader
        event={event}
        client={client}
        estimate={estimate}
        quoteRequest={quoteRequest}
      />

      <Tabs defaultValue="overview">
        <TabsList className="grid grid-cols-7 w-full">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="menu">Menu</TabsTrigger>
          <TabsTrigger value="shopping">Shopping</TabsTrigger>
          <TabsTrigger value="prep">Prep</TabsTrigger>
          <TabsTrigger value="equipment">Logistics</TabsTrigger>
          <TabsTrigger value="notes">Notes</TabsTrigger>
          <TabsTrigger value="checklist">Checklist</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="mt-4">
          <OverviewTab
            event={event}
            client={client}
            estimate={estimate}
            quoteRequest={quoteRequest}
            menu={menu}
          />
        </TabsContent>

        <TabsContent value="menu" className="mt-4">
          <MenuDietaryTab quoteRequest={quoteRequest} menu={menu} />
        </TabsContent>

        <TabsContent value="shopping" className="mt-4">
          <ShoppingList eventId={event.id} />
        </TabsContent>

        <TabsContent value="prep" className="mt-4">
          <PrepScheduleTab eventId={event.id} event={event} />
        </TabsContent>

        <TabsContent value="equipment" className="mt-4">
          <EquipmentTab quoteRequest={quoteRequest} />
        </TabsContent>

        <TabsContent value="notes" className="mt-4">
          <NotesTab event={event} />
        </TabsContent>

        <TabsContent value="checklist" className="mt-4">
          <ChecklistTab event={event} />
        </TabsContent>
      </Tabs>
    </div>
  );
}

// ─── Header card ────────────────────────────────────────────────────────────

function EventHeader({
  event,
  client,
  estimate,
  quoteRequest,
}: {
  event: EventRow;
  client: ClientRow | null;
  estimate: EstimateRow | null;
  quoteRequest: QuoteRequestRow | null;
}) {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const canViewSales = useCanViewSales();
  const days = daysUntil(event.eventDate);

  const statusMutation = useMutation({
    mutationFn: async (newStatus: string) => {
      const res = await apiRequest("PATCH", `/api/events/${event.id}`, { status: newStatus });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/events/${event.id}/full`] });
      queryClient.invalidateQueries({ queryKey: ["/api/events"] });
      toast({ title: "Status updated" });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to update status.", variant: "destructive" });
    },
  });

  const displayName = client
    ? `${client.firstName} ${client.lastName}${client.company ? ` · ${client.company}` : ""}`
    : quoteRequest
    ? `${quoteRequest.firstName} ${quoteRequest.lastName}`
    : "Unknown client";

  const phone = client?.phone || quoteRequest?.phone;
  const email = client?.email || quoteRequest?.email;

  return (
    <Card>
      <CardContent className="p-5">
        <div className="flex items-start justify-between gap-3">
          <div className="min-w-0">
            <h2 className="text-2xl font-bold">{displayName}</h2>
            <div className="mt-1 text-sm text-muted-foreground flex flex-wrap gap-x-4 gap-y-1">
              {email && (
                <a
                  href={`mailto:${email}`}
                  className="flex items-center gap-1 hover:text-primary"
                >
                  <Mail className="h-3.5 w-3.5" />
                  {email}
                </a>
              )}
              {phone && (
                <a
                  href={`tel:${phone}`}
                  className="flex items-center gap-1 hover:text-primary"
                >
                  <Phone className="h-3.5 w-3.5" />
                  {phone}
                </a>
              )}
            </div>
          </div>
          <div className="flex flex-col items-end gap-2 shrink-0">
            <Select
              value={event.status}
              onValueChange={(v) => statusMutation.mutate(v)}
            >
              <SelectTrigger className="w-[160px] h-8">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="confirmed">Confirmed</SelectItem>
                <SelectItem value="in-progress">In Progress</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
                {canViewSales && <SelectItem value="cancelled">Cancelled</SelectItem>}
              </SelectContent>
            </Select>
            <div
              className={`text-sm font-semibold ${
                days < 0
                  ? "text-gray-400"
                  : days <= 2
                  ? "text-red-600"
                  : days <= 7
                  ? "text-yellow-700"
                  : "text-green-700"
              }`}
            >
              {countdownLabel(days)}
            </div>
          </div>
        </div>

        <div className="mt-3 flex flex-wrap items-center gap-2">
          <Badge variant="secondary">{event.eventType}</Badge>
          <Badge variant="outline">
            <CalendarCheck className="h-3 w-3 mr-1" />
            {formatDate(event.eventDate)}
          </Badge>
          <Badge variant="outline">
            <Clock className="h-3 w-3 mr-1" />
            {formatTime(event.startTime)} – {formatTime(event.endTime)}
          </Badge>
          <Badge variant="outline">
            <Users className="h-3 w-3 mr-1" />
            {event.guestCount} guests
          </Badge>
          {estimate && (
            <Badge variant="outline" className="text-emerald-700 border-emerald-300">
              Total {formatCents(estimate.total)}
            </Badge>
          )}
        </div>
      </CardContent>
    </Card>
  );
}

// ─── Overview tab ──────────────────────────────────────────────────────────

function OverviewTab({
  event,
  client,
  estimate,
  quoteRequest,
  menu,
}: {
  event: EventRow;
  client: ClientRow | null;
  estimate: EstimateRow | null;
  quoteRequest: QuoteRequestRow | null;
  menu: MenuRow | null;
}) {
  const [, navigate] = useLocation();
  const { toast } = useToast();
  const canViewSales = useCanViewSales();
  const [shareDialogOpen, setShareDialogOpen] = useState(false);
  const [sharedUrl, setSharedUrl] = useState<string | null>(null);
  const [sharedLinkCopied, setSharedLinkCopied] = useState(false);

  const shareMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", `/api/events/${event.id}/share`);
      return res.json() as Promise<{ publicUrl: string; viewToken: string }>;
    },
    onSuccess: (data) => {
      setSharedUrl(data.publicUrl);
      setSharedLinkCopied(false);
      setShareDialogOpen(true);
    },
    onError: () => {
      toast({
        title: "Couldn't generate link",
        description: "Please try again in a moment.",
        variant: "destructive",
      });
    },
  });

  const handleCopySharedUrl = async () => {
    if (!sharedUrl) return;
    try {
      await navigator.clipboard.writeText(sharedUrl);
      setSharedLinkCopied(true);
      setTimeout(() => setSharedLinkCopied(false), 2000);
    } catch {
      toast({
        title: "Couldn't copy",
        description: "Select and copy manually.",
        variant: "destructive",
      });
    }
  };

  const handleOpenShareEmail = () => {
    if (!sharedUrl || !client?.email) return;
    const firstName = client.firstName || "";
    const subject = encodeURIComponent("Your event page is ready ✨");
    const body = encodeURIComponent(
      `Hi ${firstName},\n\n` +
        `We're so excited to be cooking for you! Here's your personal event page — ` +
        `bookmark it and check in anytime to see the menu we're preparing, the timeline ` +
        `for the day, and what's coming up as we get closer.\n\n` +
        `${sharedUrl}\n\n` +
        `If you need to change anything, just reply to this email or reach out directly.\n\n` +
        `— The Homebites team`
    );
    window.location.href = `mailto:${client.email}?subject=${subject}&body=${body}`;
  };

  const allergies = quoteRequest?.dietary?.allergies ?? [];
  const restrictions = quoteRequest?.dietary?.restrictions ?? [];
  const dietaryNotes = quoteRequest?.dietary?.specialNotes ?? null;
  const hasDietaryRedFlags = allergies.length > 0;

  const venueAddressParts = [
    quoteRequest?.venueName,
    (quoteRequest?.venueHasKitchen != null
      ? quoteRequest.venueHasKitchen
        ? "venue kitchen available"
        : "no venue kitchen"
      : null),
  ].filter(Boolean);

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
      {hasDietaryRedFlags && (
        <Card className="md:col-span-2 border-red-300 bg-red-50">
          <CardContent className="p-4">
            <div className="flex items-start gap-3">
              <AlertTriangle className="h-5 w-5 text-red-600 shrink-0 mt-0.5" />
              <div>
                <p className="font-semibold text-red-800">Allergies flagged</p>
                <div className="mt-1 flex flex-wrap gap-1.5">
                  {allergies.map((a) => (
                    <Badge
                      key={a}
                      className="bg-red-100 text-red-800 border-red-300 text-xs"
                    >
                      {titleCase(a)}
                    </Badge>
                  ))}
                </div>
                {dietaryNotes && (
                  <p className="mt-2 text-sm text-red-900">{dietaryNotes}</p>
                )}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
            Client
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm space-y-1">
          {client ? (
            <>
              <p className="font-medium">
                {client.firstName} {client.lastName}
              </p>
              {client.company && <p>{client.company}</p>}
              {client.address && (
                <p className="text-muted-foreground">
                  {client.address}
                  {client.city ? `, ${client.city}` : ""}
                  {client.state ? `, ${client.state}` : ""}
                  {client.zip ? ` ${client.zip}` : ""}
                </p>
              )}
              <Badge
                variant="outline"
                className="mt-1 text-xs border-emerald-300 text-emerald-700"
              >
                {titleCase(client.type)}
              </Badge>
            </>
          ) : (
            <p className="text-muted-foreground">No client record</p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
            Venue
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm">
          <p className="font-medium">{event.venue}</p>
          {venueAddressParts.length > 0 && (
            <p className="text-muted-foreground mt-1">
              {venueAddressParts.join(" · ")}
            </p>
          )}
          {quoteRequest?.venueHasKitchen === false && (
            <div className="mt-2 flex items-center gap-1 text-amber-700 text-xs">
              <AlertTriangle className="h-3 w-3" />
              No onsite kitchen — prep everything offsite
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
            Service
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm space-y-1">
          {menu?.name && (
            <p>
              <span className="text-muted-foreground">Menu: </span>
              <span className="font-medium">{menu.name}</span>
            </p>
          )}
          {quoteRequest?.menuTheme && (
            <p>
              <span className="text-muted-foreground">Theme: </span>
              <span className="font-medium">{titleCase(quoteRequest.menuTheme)}</span>
              {quoteRequest.menuTier && (
                <span className="text-muted-foreground"> · {titleCase(quoteRequest.menuTier)}</span>
              )}
            </p>
          )}
          {quoteRequest?.serviceType && (
            <p>
              <span className="text-muted-foreground">Service type: </span>
              <span className="font-medium">{titleCase(quoteRequest.serviceType)}</span>
            </p>
          )}
          {quoteRequest?.serviceStyle && (
            <p>
              <span className="text-muted-foreground">Style: </span>
              <span className="font-medium">{titleCase(quoteRequest.serviceStyle)}</span>
            </p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
            Timing
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm space-y-1">
          <p>
            <span className="text-muted-foreground">Service: </span>
            <span className="font-medium">
              {formatTime(event.startTime)} – {formatTime(event.endTime)}
            </span>
          </p>
          {quoteRequest?.hasCocktailHour && (quoteRequest.cocktailStartTime || quoteRequest.cocktailEndTime) && (
            <p>
              <span className="text-muted-foreground">Cocktail hour: </span>
              <span className="font-medium">
                {quoteRequest.cocktailStartTime} – {quoteRequest.cocktailEndTime}
              </span>
            </p>
          )}
          {(quoteRequest?.mainMealStartTime || quoteRequest?.mainMealEndTime) && (
            <p>
              <span className="text-muted-foreground">Main meal: </span>
              <span className="font-medium">
                {quoteRequest?.mainMealStartTime} – {quoteRequest?.mainMealEndTime}
              </span>
            </p>
          )}
        </CardContent>
      </Card>

      {restrictions.length > 0 && (
        <Card className="md:col-span-2">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
              Dietary Restrictions
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-1.5">
              {restrictions.map((r) => (
                <Badge key={r} variant="secondary">
                  {titleCase(r)}
                </Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {quoteRequest?.specialRequests && (
        <Card className="md:col-span-2">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wide">
              Special Requests
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm whitespace-pre-wrap">{quoteRequest.specialRequests}</p>
          </CardContent>
        </Card>
      )}

      {canViewSales && (
        <Card className="md:col-span-2">
          <CardContent className="p-3 flex flex-wrap gap-2">
            <Button
              size="sm"
              className="bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white"
              onClick={() => shareMutation.mutate()}
              disabled={shareMutation.isPending}
            >
              <Share2 className="h-3.5 w-3.5 mr-1.5" />
              {shareMutation.isPending ? "Generating..." : "Share with Customer"}
            </Button>
            {estimate && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => navigate(`/estimates/${estimate.id}/view`)}
              >
                <FileText className="h-3.5 w-3.5 mr-1.5" />
                View Quote #{estimate.id}
              </Button>
            )}
            {quoteRequest && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => navigate(`/quote-requests?id=${quoteRequest.id}`)}
              >
                <ExternalLink className="h-3.5 w-3.5 mr-1.5" />
                Inquiry #{quoteRequest.id}
              </Button>
            )}
            {client && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => navigate(`/clients/${client.id}`)}
              >
                <Users className="h-3.5 w-3.5 mr-1.5" />
                Client Record
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {/* ─── Share with Customer dialog ────────────────────────────────── */}
      <Dialog open={shareDialogOpen} onOpenChange={setShareDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Customer event page is ready</DialogTitle>
            <DialogDescription>
              Copy this link and send it to {client?.firstName ?? "the customer"}. They'll
              see a warm, celebration-focused view of their event — menu, timeline,
              milestones, and a way to reach you directly. No login required.
            </DialogDescription>
          </DialogHeader>
          {sharedUrl && (
            <div className="my-4 space-y-3">
              <div className="flex items-center gap-2 p-3 bg-gray-50 rounded-md border">
                <LinkIcon className="h-4 w-4 text-gray-500 shrink-0" />
                <code className="flex-1 text-xs text-gray-800 break-all select-all">
                  {sharedUrl}
                </code>
              </div>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={handleCopySharedUrl}
                >
                  <Copy className="h-4 w-4 mr-2" />
                  {sharedLinkCopied ? "Copied!" : "Copy Link"}
                </Button>
                {client?.email && (
                  <Button
                    className="flex-1 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600"
                    onClick={handleOpenShareEmail}
                  >
                    <Mail className="h-4 w-4 mr-2" />
                    Open Email Draft
                  </Button>
                )}
              </div>
            </div>
          )}
          <DialogFooter>
            <Button onClick={() => setShareDialogOpen(false)}>Done</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ─── Menu & Dietary tab ────────────────────────────────────────────────────

function MenuDietaryTab({
  quoteRequest,
  menu,
}: {
  quoteRequest: QuoteRequestRow | null;
  menu: MenuRow | null;
}) {
  const canViewFinancials = useCanViewFinancials();
  if (!quoteRequest) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          <UtensilsCrossed className="h-8 w-8 mx-auto mb-2 opacity-40" />
          <p>No menu details linked to this event.</p>
        </CardContent>
      </Card>
    );
  }

  // Group menu selections by category
  const grouped: Record<string, Array<{ name: string; upcharge?: number }>> = {};
  for (const sel of quoteRequest.menuSelections ?? []) {
    if (!grouped[sel.category]) grouped[sel.category] = [];
    grouped[sel.category].push({ name: sel.name, upcharge: sel.upcharge });
  }

  const tierPackage = menu?.packages?.find((p) => p.tierKey === quoteRequest.menuTier);
  const perPersonCents = tierPackage?.pricePerPersonCents;

  return (
    <div className="space-y-4">
      {/* Menu header */}
      <Card>
        <CardContent className="p-4">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <p className="text-sm text-muted-foreground">Theme</p>
              <p className="text-lg font-semibold">
                {titleCase(quoteRequest.menuTheme) || "—"}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Tier</p>
              <p className="text-lg font-semibold">
                {titleCase(quoteRequest.menuTier) || "—"}
              </p>
            </div>
            {canViewFinancials && perPersonCents != null && (
              <div>
                <p className="text-sm text-muted-foreground">Per person</p>
                <p className="text-lg font-semibold text-emerald-700">
                  {formatCents(perPersonCents)}
                </p>
              </div>
            )}
            <div>
              <p className="text-sm text-muted-foreground">Guests</p>
              <p className="text-lg font-semibold">{quoteRequest.guestCount}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Menu selections */}
      {Object.keys(grouped).length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold uppercase tracking-wide">
              Main Menu
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {Object.entries(grouped).map(([category, items]) => (
                <div key={category}>
                  <p className="text-xs font-semibold text-muted-foreground uppercase mb-1">
                    {titleCase(category)}
                  </p>
                  <ul className="space-y-0.5">
                    {items.map((it, i) => (
                      <li
                        key={`${category}-${i}`}
                        className="text-sm flex items-center justify-between"
                      >
                        <span>• {it.name}</span>
                        {canViewFinancials && it.upcharge ? (
                          <span className="text-xs text-muted-foreground">
                            +${it.upcharge.toFixed(2)}/person
                          </span>
                        ) : null}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Appetizers */}
      {quoteRequest.appetizers && quoteRequest.appetizers.selections?.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold uppercase tracking-wide">
              Appetizers
              {quoteRequest.appetizers.serviceStyle && (
                <Badge variant="outline" className="ml-2 text-xs">
                  {titleCase(quoteRequest.appetizers.serviceStyle)}
                </Badge>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-0.5">
              {quoteRequest.appetizers.selections.map((a, i) => (
                <li key={i} className="text-sm flex items-center justify-between">
                  <span>
                    • {a.itemName}{" "}
                    <span className="text-xs text-muted-foreground">
                      ({titleCase(a.category)})
                    </span>
                  </span>
                  <span className="text-xs text-muted-foreground">×{a.quantity}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Desserts */}
      {quoteRequest.desserts && quoteRequest.desserts.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold uppercase tracking-wide">
              Desserts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-0.5">
              {quoteRequest.desserts.map((d, i) => (
                <li key={i} className="text-sm flex items-center justify-between">
                  <span>• {d.itemName}</span>
                  <span className="text-xs text-muted-foreground">×{d.quantity}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Beverages */}
      {quoteRequest.beverages && (quoteRequest.beverages.hasNonAlcoholic || quoteRequest.beverages.hasAlcoholic) && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold uppercase tracking-wide flex items-center gap-2">
              <Wine className="h-4 w-4" />
              Beverages
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm space-y-1">
            {quoteRequest.beverages.hasNonAlcoholic && <p>• Non-alcoholic beverages</p>}
            {quoteRequest.beverages.hasAlcoholic && (
              <>
                <p>
                  • Alcohol service
                  {quoteRequest.beverages.bartendingType
                    ? ` (${titleCase(quoteRequest.beverages.bartendingType)})`
                    : ""}
                </p>
                {quoteRequest.beverages.liquorQuality && (
                  <p className="ml-3 text-xs text-muted-foreground">
                    {titleCase(quoteRequest.beverages.liquorQuality)} liquor
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// ─── Prep schedule tab ─────────────────────────────────────────────────────

interface ShoppingRecipe {
  recipeId: number;
  recipeName: string;
  scaledBy: number;
  laborHoursPerBatch: number;
}

interface ShoppingListPayload {
  totalLaborHours: number;
  totalLaborCost: number;
  resolvedRecipes: ShoppingRecipe[];
}

function PrepScheduleTab({ eventId, event }: { eventId: number; event: EventRow }) {
  const canViewFinancials = useCanViewFinancials();
  const { data, isLoading } = useQuery<ShoppingListPayload>({
    queryKey: [`/api/quotes/events/${eventId}/shopping-list`],
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (!data || data.resolvedRecipes.length === 0) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          <ChefHat className="h-8 w-8 mx-auto mb-2 opacity-40" />
          <p>No recipes linked — the shopping list has no resolved recipes yet.</p>
        </CardContent>
      </Card>
    );
  }

  // Sort recipes by labor hours descending so the longest prep starts earliest.
  const recipes = [...data.resolvedRecipes].sort((a, b) => {
    const aTotal = a.laborHoursPerBatch * Math.max(1, a.scaledBy);
    const bTotal = b.laborHoursPerBatch * Math.max(1, b.scaledBy);
    return bTotal - aTotal;
  });

  // "Start by" time = event start minus cumulative prep hours (longest first).
  const eventStart = new Date(event.startTime);

  return (
    <div className="space-y-4">
      <Card>
        <CardContent className="p-4 flex flex-wrap items-center gap-4 text-sm">
          <div>
            <p className="text-muted-foreground">Total prep</p>
            <p className="text-xl font-semibold">
              {data.totalLaborHours.toFixed(1)}h
            </p>
          </div>
          {canViewFinancials && data.totalLaborCost != null && (
            <div>
              <p className="text-muted-foreground">Labor cost</p>
              <p className="text-xl font-semibold text-emerald-700">
                {formatCents(data.totalLaborCost)}
              </p>
            </div>
          )}
          <div className="ml-auto text-xs text-muted-foreground max-w-xs text-right">
            v1: backwards-scheduled from event start, longest jobs first. Mike can override
            ordering mentally — a smart scheduler with dependencies is on the roadmap.
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="p-0">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-xs uppercase text-muted-foreground">
              <tr>
                <th className="text-left px-4 py-2">Recipe</th>
                <th className="text-right px-4 py-2">Batches</th>
                <th className="text-right px-4 py-2">Hrs / batch</th>
                <th className="text-right px-4 py-2">Total hrs</th>
                <th className="text-right px-4 py-2">Start by</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {recipes.map((r) => {
                const batches = Math.max(1, r.scaledBy);
                const totalHours = r.laborHoursPerBatch * batches;
                const startBy = new Date(
                  eventStart.getTime() - totalHours * 60 * 60 * 1000
                );
                return (
                  <tr key={r.recipeId} className="hover:bg-gray-50">
                    <td className="px-4 py-2 font-medium">{r.recipeName}</td>
                    <td className="px-4 py-2 text-right">{batches}</td>
                    <td className="px-4 py-2 text-right text-muted-foreground">
                      {r.laborHoursPerBatch.toFixed(1)}
                    </td>
                    <td className="px-4 py-2 text-right font-semibold">
                      {totalHours.toFixed(1)}
                    </td>
                    <td className="px-4 py-2 text-right text-muted-foreground">
                      {startBy.toLocaleDateString("en-US", {
                        month: "short",
                        day: "numeric",
                      })}{" "}
                      {startBy.toLocaleTimeString("en-US", {
                        hour: "numeric",
                        minute: "2-digit",
                      })}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </CardContent>
      </Card>
    </div>
  );
}

// ─── Equipment & Logistics tab ────────────────────────────────────────────

function EquipmentTab({ quoteRequest }: { quoteRequest: QuoteRequestRow | null }) {
  if (!quoteRequest) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          <Package className="h-8 w-8 mx-auto mb-2 opacity-40" />
          <p>No logistics data linked to this event.</p>
        </CardContent>
      </Card>
    );
  }

  const equipmentItems = quoteRequest.equipment?.items ?? [];
  const equipmentNotes = quoteRequest.equipment?.otherNotes ?? null;
  const recommendedStaff = quoteRequest.aiAnalysis?.recommendedStaffCount;

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold uppercase tracking-wide">
              Venue
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm">
            <p>
              <span className="text-muted-foreground">Kitchen: </span>
              {quoteRequest.venueHasKitchen == null
                ? "Unknown"
                : quoteRequest.venueHasKitchen
                ? "Available onsite"
                : "None — prep offsite"}
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-semibold uppercase tracking-wide flex items-center gap-2">
              <UserCheck className="h-4 w-4" />
              Recommended Staff
            </CardTitle>
          </CardHeader>
          <CardContent className="text-sm">
            {recommendedStaff != null ? (
              <p className="text-2xl font-bold">{recommendedStaff}</p>
            ) : (
              <p className="text-muted-foreground">No AI recommendation yet</p>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold uppercase tracking-wide">
            Rentals
          </CardTitle>
        </CardHeader>
        <CardContent>
          {equipmentItems.length === 0 ? (
            <p className="text-sm text-muted-foreground">No rentals on the estimate.</p>
          ) : (
            <ul className="space-y-1">
              {equipmentItems.map((e, i) => (
                <li key={i} className="text-sm flex items-center justify-between">
                  <span>• {e.item}</span>
                  <span className="text-xs text-muted-foreground">×{e.quantity}</span>
                </li>
              ))}
            </ul>
          )}
          {equipmentNotes && (
            <>
              <Separator className="my-2" />
              <p className="text-sm whitespace-pre-wrap">{equipmentNotes}</p>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// ─── Notes tab ─────────────────────────────────────────────────────────────

function NotesTab({ event }: { event: EventRow }) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [notes, setNotes] = useState<string>(event.notes ?? "");

  React.useEffect(() => {
    setNotes(event.notes ?? "");
  }, [event.id, event.notes]);

  const notesMutation = useMutation({
    mutationFn: async (value: string) => {
      const res = await apiRequest("PATCH", `/api/events/${event.id}`, { notes: value });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/events/${event.id}/full`] });
      toast({ title: "Notes saved" });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to save notes.", variant: "destructive" });
    },
  });

  const handleBlur = () => {
    if (notes !== (event.notes ?? "")) {
      notesMutation.mutate(notes);
    }
  };

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-semibold uppercase tracking-wide flex items-center gap-2">
            <StickyNote className="h-4 w-4" />
            Internal Notes
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Textarea
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            onBlur={handleBlur}
            placeholder="Anything the team needs to know about this event. Saves on blur."
            rows={8}
          />
        </CardContent>
      </Card>

      <Card className="border-dashed">
        <CardContent className="p-4 text-sm text-muted-foreground">
          <p className="font-semibold text-foreground mb-1">Email &amp; call history — coming soon</p>
          <p>
            The schema is ready (communications can link to events), but the thread view isn't
            wired yet. For now, client-level email/call history lives on the client record.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

// ─── Checklist tab ─────────────────────────────────────────────────────────

function ChecklistTab({ event }: { event: EventRow }) {
  const { toast } = useToast();
  const completed = new Set(event.completedTasks ?? []);

  const toggleMutation = useMutation({
    mutationFn: async ({ taskId, done }: { taskId: string; done: boolean }) => {
      const res = await apiRequest("PATCH", `/api/events/${event.id}/checklist`, { taskId, done });
      return res.json();
    },
    onMutate: async ({ taskId, done }) => {
      await queryClient.cancelQueries({ queryKey: [`/api/events/${event.id}/full`] });
      const previous = queryClient.getQueryData<FullEventPayload>([`/api/events/${event.id}/full`]);
      if (previous) {
        const nextTasks = done
          ? Array.from(new Set([...(previous.event.completedTasks ?? []), taskId]))
          : (previous.event.completedTasks ?? []).filter((t) => t !== taskId);
        queryClient.setQueryData<FullEventPayload>(
          [`/api/events/${event.id}/full`],
          { ...previous, event: { ...previous.event, completedTasks: nextTasks } }
        );
      }
      return { previous };
    },
    onError: (_err, _vars, ctx) => {
      if (ctx?.previous) {
        queryClient.setQueryData([`/api/events/${event.id}/full`], ctx.previous);
      }
      toast({ title: "Error", description: "Failed to update checklist.", variant: "destructive" });
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: [`/api/events/${event.id}/full`] });
    },
  });

  return (
    <div className="space-y-4">
      {CHECKLIST.map((stage) => {
        const stageIds = stage.items.map((i) => i.id);
        const doneCount = stageIds.filter((id) => completed.has(id)).length;
        const pct = Math.round((doneCount / stageIds.length) * 100);
        return (
          <Card key={stage.key}>
            <CardHeader className="pb-2">
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-base font-semibold flex items-center gap-2">
                    <ClipboardCheck className="h-4 w-4" />
                    {stage.title}
                  </CardTitle>
                  <p className="text-xs text-muted-foreground mt-0.5">{stage.description}</p>
                </div>
                <div className="text-sm font-semibold text-muted-foreground">
                  {doneCount} / {stageIds.length}
                </div>
              </div>
              <Progress value={pct} className="h-1.5 mt-2" />
            </CardHeader>
            <CardContent className="pt-0">
              <ul className="space-y-2">
                {stage.items.map((it) => {
                  const isDone = completed.has(it.id);
                  return (
                    <li key={it.id} className="flex items-center gap-2">
                      <Checkbox
                        checked={isDone}
                        onCheckedChange={(v) =>
                          toggleMutation.mutate({ taskId: it.id, done: !!v })
                        }
                        id={`task-${it.id}`}
                      />
                      <label
                        htmlFor={`task-${it.id}`}
                        className={`text-sm cursor-pointer ${
                          isDone ? "line-through text-muted-foreground" : ""
                        }`}
                      >
                        {it.label}
                      </label>
                    </li>
                  );
                })}
              </ul>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
