import React, { useState, useCallback } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import ShoppingList from "@/components/shopping/ShoppingList";

import {
  Sparkles,
  ArrowRight,
  Check,
  Clock,
  Users,
  Calendar,
  MapPin,
  ChefHat,
  UtensilsCrossed,
  Wine,
  AlertTriangle,
  DollarSign,
  FileText,
  Loader2,
  Inbox,
  RefreshCw,
  ExternalLink,
  TrendingUp,
  Star,
  Timer,
  UserCheck,
} from "lucide-react";

// ─── Types ────────────────────────────────────────────────────────────────────

interface QuoteRequest {
  id: number;
  status: "draft" | "submitted" | "reviewing" | "quoted" | "converted" | "disqualified" | "expired" | "archived";
  disqualificationReason: string | null;
  rawLeadId: number | null;
  firstName: string;
  lastName: string;
  email: string;
  phone: string | null;
  partnerFirstName: string | null;
  partnerLastName: string | null;
  companyName: string | null;
  eventType: string;
  eventDate: string | null;
  guestCount: number;
  eventStartTime: string | null;
  eventEndTime: string | null;
  venueName: string | null;
  venueHasKitchen: boolean | null;
  serviceType: string | null;
  serviceStyle: string | null;
  menuTheme: string | null;
  menuTier: string | null;
  menuSelections: Array<{ name: string; category: string; upcharge?: number }>;
  appetizers: {
    serviceStyle?: string;
    selections: Array<{
      category: string;
      itemName: string;
      pricePerPiece: number;
      quantity: number;
      subtotal: number;
    }>;
  } | null;
  desserts: Array<{
    itemName: string;
    pricePerPiece: number;
    quantity: number;
    subtotal: number;
  }> | null;
  beverages: {
    hasNonAlcoholic: boolean;
    hasAlcoholic: boolean;
    bartendingType?: string;
    liquorQuality?: string;
  } | null;
  equipment: {
    items: Array<{
      item: string;
      pricePerUnit: number;
      quantity: number;
      subtotal: number;
    }>;
    otherNotes?: string;
  } | null;
  dietary: {
    restrictions?: string[];
    allergies?: string[];
    specialNotes?: string;
  } | null;
  estimatedPerPersonCents: number | null;
  estimatedSubtotalCents: number | null;
  estimatedTotalCents: number | null;
  aiAnalysis: {
    eventComplexityScore?: number;
    estimatedPrepHours?: number;
    recommendedStaffCount?: number;
    suggestedUpsells?: Array<{ item: string; reason: string; estimatedValue: number }>;
    suggestedAlternatives?: Array<{ original: string; suggestion: string; reason: string }>;
    pricingConfidence?: number;
    marginEstimate?: number;
    autoGeneratedNotes?: string;
    analyzedAt?: string;
  } | null;
  source: string | null;
  referralDetail: string | null;
  discountPercent: string | null;
  decisionTimeline: string | null;
  specialRequests: string | null;
  internalNotes: string | null;
  opportunityId: number | null;
  estimateId: number | null;
  submittedAt: string | null;
  convertedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

interface ConvertResponse {
  client: { id: number };
  opportunity: { id: number };
  estimate: { id: number };
  message: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatCents(cents: number | null): string {
  if (cents === null || cents === undefined) return "--";
  return `$${(cents / 100).toFixed(2)}`;
}

function relativeTime(dateString: string | null): string {
  if (!dateString) return "--";
  const now = Date.now();
  const then = new Date(dateString).getTime();
  const diffMs = now - then;
  const diffMinutes = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMinutes < 1) return "Just now";
  if (diffMinutes < 60) return `${diffMinutes}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays === 1) return "Yesterday";
  return `${diffDays}d ago`;
}

function formatDate(dateString: string | null): string {
  if (!dateString) return "--";
  return new Date(dateString).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatTime(timeString: string | null): string {
  if (!timeString) return "";
  return timeString;
}

const STATUS_COLORS: Record<string, string> = {
  draft: "bg-gray-100 text-gray-700 border-gray-300",
  submitted: "bg-blue-100 text-blue-700 border-blue-300",
  reviewing: "bg-yellow-100 text-yellow-700 border-yellow-300",
  quoted: "bg-purple-100 text-purple-700 border-purple-300",
  converted: "bg-green-100 text-green-700 border-green-300",
  disqualified: "bg-orange-100 text-orange-700 border-orange-300",
  expired: "bg-red-100 text-red-700 border-red-300",
  archived: "bg-gray-100 text-gray-500 border-gray-300",
};

const STATUS_LABELS: Record<string, string> = {
  draft: "Draft",
  submitted: "New",
  reviewing: "Reviewing",
  quoted: "Quoted",
  converted: "Converted",
  disqualified: "Disqualified",
  expired: "Expired",
  archived: "Archived",
};

function complexityLabel(score: number): string {
  if (score <= 3) return "Simple";
  if (score <= 6) return "Moderate";
  if (score <= 8) return "Complex";
  return "Very Complex";
}

function complexityDotColor(score: number | undefined): string {
  if (!score) return "bg-gray-300";
  if (score <= 3) return "bg-green-500";
  if (score <= 6) return "bg-yellow-500";
  return "bg-red-500";
}

function marginColor(margin: number | undefined): string {
  if (margin === undefined) return "text-gray-500";
  if (margin > 0.3) return "text-green-600";
  if (margin >= 0.25) return "text-yellow-600";
  return "text-red-600";
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function QuoteRequests() {
  const { toast } = useToast();
  const [, navigate] = useLocation();
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState("all");
  const [convertDialogOpen, setConvertDialogOpen] = useState(false);
  const [disqualifyDialogOpen, setDisqualifyDialogOpen] = useState(false);
  const [disqualifyReason, setDisqualifyReason] = useState<string>("");
  const [internalNotesValue, setInternalNotesValue] = useState<string>("");
  const [notesInitializedForId, setNotesInitializedForId] = useState<number | null>(null);

  // ─── Data fetching ────────────────────────────────────────────────────────

  const {
    data: quoteRequests = [],
    isLoading,
    isError,
  } = useQuery<QuoteRequest[]>({
    queryKey: ["/api/quotes/quote-requests"],
  });

  const selectedRequest = quoteRequests.find((qr) => qr.id === selectedId) ?? null;

  // Initialize internal notes when selection changes
  React.useEffect(() => {
    if (selectedRequest && selectedRequest.id !== notesInitializedForId) {
      setInternalNotesValue(selectedRequest.internalNotes ?? "");
      setNotesInitializedForId(selectedRequest.id);
    }
  }, [selectedRequest, notesInitializedForId]);

  // ─── Mutations ────────────────────────────────────────────────────────────

  const statusMutation = useMutation({
    mutationFn: async ({
      id,
      status,
      disqualificationReason,
    }: {
      id: number;
      status: string;
      disqualificationReason?: string;
    }) => {
      const payload: Record<string, unknown> = { status };
      if (disqualificationReason !== undefined) {
        payload.disqualificationReason = disqualificationReason;
      }
      const res = await apiRequest("PATCH", `/api/quotes/quote-requests/${id}`, payload);
      return res.json();
    },
    onMutate: async ({ id, status, disqualificationReason }) => {
      await queryClient.cancelQueries({ queryKey: ["/api/quotes/quote-requests"] });
      const previous = queryClient.getQueryData<QuoteRequest[]>(["/api/quotes/quote-requests"]);
      queryClient.setQueryData<QuoteRequest[]>(["/api/quotes/quote-requests"], (old) =>
        (old ?? []).map((qr) =>
          qr.id === id
            ? {
                ...qr,
                status: status as QuoteRequest["status"],
                ...(disqualificationReason !== undefined ? { disqualificationReason } : {}),
              }
            : qr
        )
      );
      return { previous };
    },
    onError: (_err, _vars, context) => {
      if (context?.previous) {
        queryClient.setQueryData(["/api/quotes/quote-requests"], context.previous);
      }
      toast({ title: "Error", description: "Failed to update status.", variant: "destructive" });
    },
    onSettled: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/quotes/quote-requests"] });
    },
  });

  const handleStatusChange = (value: string) => {
    if (!selectedRequest) return;
    if (value === "disqualified") {
      setDisqualifyReason(selectedRequest.disqualificationReason ?? "");
      setDisqualifyDialogOpen(true);
      return;
    }
    statusMutation.mutate({ id: selectedRequest.id, status: value });
  };

  const confirmDisqualify = () => {
    if (!selectedRequest) return;
    const reason = disqualifyReason.trim();
    if (!reason) {
      toast({
        title: "Reason required",
        description: "Please enter a short reason before disqualifying.",
        variant: "destructive",
      });
      return;
    }
    statusMutation.mutate({
      id: selectedRequest.id,
      status: "disqualified",
      disqualificationReason: reason,
    });
    setDisqualifyDialogOpen(false);
  };

  const notesMutation = useMutation({
    mutationFn: async ({ id, internalNotes }: { id: number; internalNotes: string }) => {
      const res = await apiRequest("PATCH", `/api/quotes/quote-requests/${id}`, { internalNotes });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/quotes/quote-requests"] });
      toast({ title: "Saved", description: "Internal notes updated." });
    },
    onError: () => {
      toast({ title: "Error", description: "Failed to save notes.", variant: "destructive" });
    },
  });

  const analyzeMutation = useMutation({
    mutationFn: async (id: number) => {
      const res = await apiRequest("POST", `/api/quotes/quote-requests/${id}/analyze`);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/quotes/quote-requests"] });
      toast({ title: "Analysis Complete", description: "AI analysis has been updated." });
    },
    onError: () => {
      toast({ title: "Error", description: "AI analysis failed. Please try again.", variant: "destructive" });
    },
  });

  const convertMutation = useMutation({
    mutationFn: async (id: number) => {
      const res = await apiRequest("POST", `/api/quotes/quote-requests/${id}/convert`);
      return res.json() as Promise<ConvertResponse>;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["/api/quotes/quote-requests"] });
      setConvertDialogOpen(false);
      toast({
        title: "Converted Successfully",
        description: data.message || "Client, opportunity, and estimate created.",
      });
    },
    onError: () => {
      toast({ title: "Error", description: "Conversion failed. Please try again.", variant: "destructive" });
    },
  });

  // ─── Handlers ─────────────────────────────────────────────────────────────

  const handleNotesBlur = useCallback(() => {
    if (selectedRequest && internalNotesValue !== (selectedRequest.internalNotes ?? "")) {
      notesMutation.mutate({ id: selectedRequest.id, internalNotes: internalNotesValue });
    }
  }, [selectedRequest, internalNotesValue, notesMutation]);

  // ─── Filtering ────────────────────────────────────────────────────────────

  const filteredRequests = React.useMemo(() => {
    let filtered = [...quoteRequests];
    if (activeTab !== "all") {
      filtered = filtered.filter((qr) => qr.status === activeTab);
    }
    // Sort by most recent first (submittedAt, then createdAt)
    filtered.sort((a, b) => {
      const dateA = new Date(a.submittedAt ?? a.createdAt).getTime();
      const dateB = new Date(b.submittedAt ?? b.createdAt).getTime();
      return dateB - dateA;
    });
    return filtered;
  }, [quoteRequests, activeTab]);

  // ─── Render helpers ───────────────────────────────────────────────────────

  const convertedResult = convertMutation.data as ConvertResponse | undefined;

  // ─── Render ───────────────────────────────────────────────────────────────

  return (
    <div className="h-full">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">Quote Requests</h1>
          <p className="text-muted-foreground mt-1">
            Manage incoming quote requests and AI-powered insights
          </p>
        </div>
        <Badge variant="outline" className="text-sm py-1 px-3">
          {quoteRequests.length} total request{quoteRequests.length !== 1 ? "s" : ""}
        </Badge>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 min-h-[calc(100vh-12rem)]">
        {/* ─── Left Panel: Quote List (60%) ──────────────────────────────── */}
        <div className="w-full lg:w-[60%] flex flex-col">
          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="mb-4 flex-wrap">
              <TabsTrigger value="all">All</TabsTrigger>
              <TabsTrigger value="submitted">New</TabsTrigger>
              <TabsTrigger value="reviewing">Reviewing</TabsTrigger>
              <TabsTrigger value="quoted">Quoted</TabsTrigger>
              <TabsTrigger value="converted">Converted</TabsTrigger>
              <TabsTrigger value="disqualified">Disqualified</TabsTrigger>
              <TabsTrigger value="archived">Archived</TabsTrigger>
            </TabsList>

            {/* Single content area since we filter manually */}
            <div className="space-y-3 overflow-y-auto max-h-[calc(100vh-16rem)] pr-1">
              {isLoading && (
                <div className="flex items-center justify-center py-16">
                  <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
                </div>
              )}

              {isError && (
                <Card className="border-red-200 bg-red-50">
                  <CardContent className="py-8 text-center text-red-600">
                    <AlertTriangle className="h-8 w-8 mx-auto mb-2" />
                    <p>Failed to load quote requests. Please refresh the page.</p>
                  </CardContent>
                </Card>
              )}

              {!isLoading && !isError && filteredRequests.length === 0 && (
                <Card>
                  <CardContent className="py-12 text-center text-muted-foreground">
                    <Inbox className="h-12 w-12 mx-auto mb-3 opacity-40" />
                    <p className="text-lg font-medium">No quote requests found</p>
                    <p className="text-sm mt-1">
                      {activeTab === "all"
                        ? "New requests will appear here when submitted."
                        : `No requests with "${STATUS_LABELS[activeTab] ?? activeTab}" status.`}
                    </p>
                  </CardContent>
                </Card>
              )}

              {filteredRequests.map((qr) => (
                <Card
                  key={qr.id}
                  className={`cursor-pointer transition-all hover:shadow-md ${
                    selectedId === qr.id
                      ? "ring-2 ring-primary shadow-md"
                      : "hover:border-gray-300"
                  }`}
                  onClick={() => setSelectedId(qr.id)}
                >
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-semibold text-base truncate">
                            {qr.firstName} {qr.lastName}
                          </span>
                          <Badge variant="secondary" className="text-xs shrink-0">
                            {qr.eventType}
                          </Badge>
                          <span className="text-sm text-muted-foreground shrink-0">
                            <Users className="h-3.5 w-3.5 inline mr-1" />
                            {qr.guestCount} guests
                          </span>
                        </div>

                        <div className="flex items-center gap-3 mt-2 text-sm text-muted-foreground flex-wrap">
                          {qr.eventDate && (
                            <span className="flex items-center gap-1">
                              <Calendar className="h-3.5 w-3.5" />
                              {formatDate(qr.eventDate)}
                            </span>
                          )}
                          {(qr.menuTheme || qr.menuTier) && (
                            <span className="flex items-center gap-1">
                              <ChefHat className="h-3.5 w-3.5" />
                              {[qr.menuTheme, qr.menuTier].filter(Boolean).join(" - ")}
                            </span>
                          )}
                        </div>
                      </div>

                      <div className="flex flex-col items-end gap-2 shrink-0">
                        <Badge className={`${STATUS_COLORS[qr.status]} border text-xs`}>
                          {STATUS_LABELS[qr.status] ?? qr.status}
                        </Badge>
                        <div className="flex items-center gap-2">
                          {qr.aiAnalysis?.eventComplexityScore !== undefined && (
                            <span
                              className={`h-2.5 w-2.5 rounded-full ${complexityDotColor(
                                qr.aiAnalysis.eventComplexityScore
                              )}`}
                              title={`Complexity: ${qr.aiAnalysis.eventComplexityScore}/10`}
                            />
                          )}
                          <span className="text-xs text-muted-foreground">
                            {relativeTime(qr.submittedAt ?? qr.createdAt)}
                          </span>
                        </div>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </Tabs>
        </div>

        {/* ─── Right Panel: Detail View (40%) ────────────────────────────── */}
        <div className="w-full lg:w-[40%] overflow-y-auto max-h-[calc(100vh-12rem)]">
          {!selectedRequest ? (
            <div className="flex flex-col items-center justify-center h-full text-center py-24">
              <FileText className="h-16 w-16 text-muted-foreground/30 mb-4" />
              <p className="text-lg font-medium text-muted-foreground">
                Select a quote request to view details
              </p>
              <p className="text-sm text-muted-foreground/70 mt-1">
                Click on any request from the list
              </p>
            </div>
          ) : (
            <div className="space-y-4 pb-8">
              {/* ─── Header ──────────────────────────────────────────────── */}
              <Card>
                <CardContent className="p-5">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <h2 className="text-xl font-bold">
                        {selectedRequest.firstName} {selectedRequest.lastName}
                      </h2>
                      {selectedRequest.companyName && (
                        <p className="text-sm text-muted-foreground">{selectedRequest.companyName}</p>
                      )}
                      <div className="flex items-center gap-3 mt-1 text-sm text-muted-foreground flex-wrap">
                        <span>{selectedRequest.email}</span>
                        {selectedRequest.phone && (
                          <>
                            <span className="text-gray-300">|</span>
                            <span>{selectedRequest.phone}</span>
                          </>
                        )}
                      </div>
                    </div>
                    <div className="flex flex-col items-end gap-2 shrink-0">
                      <Select
                        value={selectedRequest.status}
                        onValueChange={handleStatusChange}
                      >
                        <SelectTrigger className="w-[140px] h-8">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="submitted">New</SelectItem>
                          <SelectItem value="reviewing">Reviewing</SelectItem>
                          <SelectItem value="quoted">Quoted</SelectItem>
                          <SelectItem value="converted">Converted</SelectItem>
                          <SelectItem value="disqualified">Disqualified</SelectItem>
                          <SelectItem value="expired">Expired</SelectItem>
                          <SelectItem value="archived">Archived</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 mt-3 flex-wrap">
                    <Badge variant="secondary">{selectedRequest.eventType}</Badge>
                    {selectedRequest.eventDate && (
                      <Badge variant="outline">
                        <Calendar className="h-3 w-3 mr-1" />
                        {formatDate(selectedRequest.eventDate)}
                      </Badge>
                    )}
                    <Badge variant="outline">
                      <Users className="h-3 w-3 mr-1" />
                      {selectedRequest.guestCount} guests
                    </Badge>
                    {selectedRequest.rawLeadId && (
                      <Badge
                        variant="outline"
                        className="cursor-pointer border-indigo-300 text-indigo-700 hover:bg-indigo-50"
                        onClick={() => navigate(`/raw-leads/${selectedRequest.rawLeadId}`)}
                      >
                        <Inbox className="h-3 w-3 mr-1" />
                        Promoted from Lead #{selectedRequest.rawLeadId}
                      </Badge>
                    )}
                  </div>

                  {selectedRequest.status === "disqualified" && selectedRequest.disqualificationReason && (
                    <div className="mt-3 rounded-md border border-orange-200 bg-orange-50 px-3 py-2 text-sm text-orange-900">
                      <span className="font-semibold">Disqualified: </span>
                      {selectedRequest.disqualificationReason}
                    </div>
                  )}

                  <Separator className="my-3" />

                  <div className="flex gap-2 flex-wrap">
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => analyzeMutation.mutate(selectedRequest.id)}
                      disabled={analyzeMutation.isPending}
                    >
                      {analyzeMutation.isPending ? (
                        <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                      ) : (
                        <Sparkles className="h-4 w-4 mr-1.5" />
                      )}
                      {analyzeMutation.isPending ? "Analyzing..." : "Re-Analyze"}
                    </Button>

                    <Button
                      size="sm"
                      onClick={() => setConvertDialogOpen(true)}
                      disabled={selectedRequest.status === "converted"}
                    >
                      {selectedRequest.status === "converted" ? (
                        <>
                          <Check className="h-4 w-4 mr-1.5" />
                          Converted
                        </>
                      ) : (
                        <>
                          <ArrowRight className="h-4 w-4 mr-1.5" />
                          Convert to Estimate
                        </>
                      )}
                    </Button>

                    {selectedRequest.opportunityId && (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => navigate(`/opportunities/${selectedRequest.opportunityId}`)}
                      >
                        <ExternalLink className="h-3.5 w-3.5 mr-1.5" />
                        Opportunity
                      </Button>
                    )}
                    {selectedRequest.estimateId && (
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => navigate(`/estimates/${selectedRequest.estimateId}/view`)}
                      >
                        <ExternalLink className="h-3.5 w-3.5 mr-1.5" />
                        Estimate
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>

              {/* ─── AI Insights Card ────────────────────────────────────── */}
              <Card className="overflow-hidden">
                <div className="bg-gradient-to-r from-purple-600 to-indigo-600 px-5 py-3">
                  <div className="flex items-center gap-2 text-white">
                    <Sparkles className="h-5 w-5" />
                    <span className="font-semibold text-base">AI Analysis</span>
                  </div>
                </div>
                <CardContent className="p-5">
                  {analyzeMutation.isPending && (
                    <div className="flex flex-col items-center py-8 text-muted-foreground">
                      <Loader2 className="h-10 w-10 animate-spin mb-3 text-purple-500" />
                      <p className="font-medium">Running AI analysis...</p>
                      <p className="text-sm mt-1">This may take a few seconds</p>
                    </div>
                  )}

                  {!analyzeMutation.isPending && !selectedRequest.aiAnalysis && (
                    <div className="flex flex-col items-center py-8 text-muted-foreground">
                      <Sparkles className="h-10 w-10 mb-3 opacity-30" />
                      <p className="font-medium">No analysis yet</p>
                      <Button
                        size="sm"
                        className="mt-3"
                        onClick={() => analyzeMutation.mutate(selectedRequest.id)}
                      >
                        <Sparkles className="h-4 w-4 mr-1.5" />
                        Run AI Analysis
                      </Button>
                    </div>
                  )}

                  {!analyzeMutation.isPending && selectedRequest.aiAnalysis && (
                    <div className="space-y-5">
                      {/* Complexity + key metrics */}
                      <div className="grid grid-cols-2 gap-4">
                        {selectedRequest.aiAnalysis.eventComplexityScore !== undefined && (
                          <div className="text-center p-3 rounded-lg bg-gray-50">
                            <div
                              className={`text-3xl font-bold ${
                                selectedRequest.aiAnalysis.eventComplexityScore <= 3
                                  ? "text-green-600"
                                  : selectedRequest.aiAnalysis.eventComplexityScore <= 6
                                  ? "text-yellow-600"
                                  : "text-red-600"
                              }`}
                            >
                              {selectedRequest.aiAnalysis.eventComplexityScore}
                              <span className="text-sm font-normal text-muted-foreground">/10</span>
                            </div>
                            <p className="text-xs text-muted-foreground mt-1">
                              {complexityLabel(selectedRequest.aiAnalysis.eventComplexityScore)}
                            </p>
                          </div>
                        )}

                        {selectedRequest.aiAnalysis.marginEstimate !== undefined && (
                          <div className="text-center p-3 rounded-lg bg-gray-50">
                            <div
                              className={`text-3xl font-bold ${marginColor(
                                selectedRequest.aiAnalysis.marginEstimate
                              )}`}
                            >
                              {Math.round(selectedRequest.aiAnalysis.marginEstimate * 100)}%
                            </div>
                            <p className="text-xs text-muted-foreground mt-1">Est. Margin</p>
                          </div>
                        )}
                      </div>

                      <div className="grid grid-cols-2 gap-3">
                        {selectedRequest.aiAnalysis.estimatedPrepHours !== undefined && (
                          <div className="flex items-center gap-2 text-sm">
                            <Timer className="h-4 w-4 text-muted-foreground shrink-0" />
                            <span>
                              <span className="font-medium">
                                {selectedRequest.aiAnalysis.estimatedPrepHours}h
                              </span>{" "}
                              prep time
                            </span>
                          </div>
                        )}
                        {selectedRequest.aiAnalysis.recommendedStaffCount !== undefined && (
                          <div className="flex items-center gap-2 text-sm">
                            <UserCheck className="h-4 w-4 text-muted-foreground shrink-0" />
                            <span>
                              <span className="font-medium">
                                {selectedRequest.aiAnalysis.recommendedStaffCount}
                              </span>{" "}
                              staff recommended
                            </span>
                          </div>
                        )}
                      </div>

                      {/* Pricing confidence */}
                      {selectedRequest.aiAnalysis.pricingConfidence !== undefined && (
                        <div>
                          <div className="flex items-center justify-between text-sm mb-1">
                            <span className="text-muted-foreground">Pricing Confidence</span>
                            <span className="font-medium">
                              {Math.round(selectedRequest.aiAnalysis.pricingConfidence * 100)}%
                            </span>
                          </div>
                          <Progress
                            value={selectedRequest.aiAnalysis.pricingConfidence * 100}
                            className="h-2"
                          />
                        </div>
                      )}

                      {/* Auto-generated notes */}
                      {selectedRequest.aiAnalysis.autoGeneratedNotes && (
                        <div className="bg-purple-50 border border-purple-200 rounded-lg p-3">
                          <p className="text-xs font-semibold text-purple-700 uppercase tracking-wide mb-1">
                            Sales Notes
                          </p>
                          <p className="text-sm text-purple-900">
                            {selectedRequest.aiAnalysis.autoGeneratedNotes}
                          </p>
                        </div>
                      )}

                      {/* Suggested upsells */}
                      {selectedRequest.aiAnalysis.suggestedUpsells &&
                        selectedRequest.aiAnalysis.suggestedUpsells.length > 0 && (
                          <div>
                            <p className="text-sm font-semibold mb-2 flex items-center gap-1.5">
                              <TrendingUp className="h-4 w-4 text-green-600" />
                              Suggested Upsells
                            </p>
                            <div className="space-y-2">
                              {selectedRequest.aiAnalysis.suggestedUpsells.map((upsell, i) => (
                                <div
                                  key={i}
                                  className="flex items-start justify-between gap-2 text-sm border rounded-md p-2"
                                >
                                  <div>
                                    <p className="font-medium">{upsell.item}</p>
                                    <p className="text-xs text-muted-foreground">{upsell.reason}</p>
                                  </div>
                                  <span className="text-green-600 font-medium whitespace-nowrap">
                                    +{formatCents(upsell.estimatedValue)}
                                  </span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                      {/* Suggested alternatives */}
                      {selectedRequest.aiAnalysis.suggestedAlternatives &&
                        selectedRequest.aiAnalysis.suggestedAlternatives.length > 0 && (
                          <div>
                            <p className="text-sm font-semibold mb-2 flex items-center gap-1.5">
                              <RefreshCw className="h-4 w-4 text-blue-600" />
                              Suggested Alternatives
                            </p>
                            <div className="space-y-2">
                              {selectedRequest.aiAnalysis.suggestedAlternatives.map((alt, i) => (
                                <div key={i} className="text-sm border rounded-md p-2">
                                  <p>
                                    <span className="text-muted-foreground line-through">
                                      {alt.original}
                                    </span>{" "}
                                    <ArrowRight className="h-3 w-3 inline mx-1" />{" "}
                                    <span className="font-medium">{alt.suggestion}</span>
                                  </p>
                                  <p className="text-xs text-muted-foreground mt-0.5">
                                    {alt.reason}
                                  </p>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                      {/* Analyzed timestamp + re-analyze */}
                      <div className="flex items-center justify-between text-xs text-muted-foreground pt-2 border-t">
                        <span>
                          Analyzed{" "}
                          {selectedRequest.aiAnalysis.analyzedAt
                            ? relativeTime(selectedRequest.aiAnalysis.analyzedAt)
                            : "recently"}
                        </span>
                        <Button
                          size="sm"
                          variant="ghost"
                          className="h-7 text-xs"
                          onClick={() => analyzeMutation.mutate(selectedRequest.id)}
                          disabled={analyzeMutation.isPending}
                        >
                          <RefreshCw
                            className={`h-3 w-3 mr-1 ${
                              analyzeMutation.isPending ? "animate-spin" : ""
                            }`}
                          />
                          Re-analyze
                        </Button>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>

              {/* ─── Event Details Card ──────────────────────────────────── */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base flex items-center gap-2">
                    <Calendar className="h-4 w-4" />
                    Event Details
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <p className="text-muted-foreground text-xs">Event Type</p>
                      <p className="font-medium">{selectedRequest.eventType}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground text-xs">Date</p>
                      <p className="font-medium">{formatDate(selectedRequest.eventDate)}</p>
                    </div>
                    <div>
                      <p className="text-muted-foreground text-xs">Time</p>
                      <p className="font-medium">
                        {selectedRequest.eventStartTime || selectedRequest.eventEndTime
                          ? `${formatTime(selectedRequest.eventStartTime)}${
                              selectedRequest.eventEndTime
                                ? ` - ${formatTime(selectedRequest.eventEndTime)}`
                                : ""
                            }`
                          : "--"}
                      </p>
                    </div>
                    <div>
                      <p className="text-muted-foreground text-xs">Guest Count</p>
                      <p className="font-medium">{selectedRequest.guestCount}</p>
                    </div>
                  </div>

                  {(selectedRequest.venueName || selectedRequest.venueHasKitchen !== null) && (
                    <>
                      <Separator />
                      <div className="grid grid-cols-2 gap-3">
                        {selectedRequest.venueName && (
                          <div>
                            <p className="text-muted-foreground text-xs">Venue</p>
                            <p className="font-medium flex items-center gap-1">
                              <MapPin className="h-3.5 w-3.5" />
                              {selectedRequest.venueName}
                            </p>
                          </div>
                        )}
                        {selectedRequest.venueHasKitchen !== null && (
                          <div>
                            <p className="text-muted-foreground text-xs">Kitchen</p>
                            <p className="font-medium">
                              {selectedRequest.venueHasKitchen ? "Available" : "No kitchen"}
                            </p>
                          </div>
                        )}
                      </div>
                    </>
                  )}

                  {selectedRequest.partnerFirstName && (
                    <>
                      <Separator />
                      <div>
                        <p className="text-muted-foreground text-xs">Partner</p>
                        <p className="font-medium">
                          {selectedRequest.partnerFirstName} {selectedRequest.partnerLastName}
                        </p>
                      </div>
                    </>
                  )}
                </CardContent>
              </Card>

              {/* ─── Service & Menu Card ─────────────────────────────────── */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base flex items-center gap-2">
                    <UtensilsCrossed className="h-4 w-4" />
                    Service & Menu
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  <div className="grid grid-cols-2 gap-3">
                    {selectedRequest.serviceType && (
                      <div>
                        <p className="text-muted-foreground text-xs">Service Type</p>
                        <p className="font-medium">{selectedRequest.serviceType}</p>
                      </div>
                    )}
                    {selectedRequest.serviceStyle && (
                      <div>
                        <p className="text-muted-foreground text-xs">Service Style</p>
                        <p className="font-medium">{selectedRequest.serviceStyle}</p>
                      </div>
                    )}
                    {selectedRequest.menuTheme && (
                      <div>
                        <p className="text-muted-foreground text-xs">Menu Theme</p>
                        <p className="font-medium">{selectedRequest.menuTheme}</p>
                      </div>
                    )}
                    {selectedRequest.menuTier && (
                      <div>
                        <p className="text-muted-foreground text-xs">Menu Tier</p>
                        <p className="font-medium">{selectedRequest.menuTier}</p>
                      </div>
                    )}
                  </div>

                  {selectedRequest.menuSelections && selectedRequest.menuSelections.length > 0 && (
                    <>
                      <Separator />
                      <p className="font-medium text-xs text-muted-foreground uppercase tracking-wide">
                        Menu Selections
                      </p>
                      {(() => {
                        const grouped: Record<string, typeof selectedRequest.menuSelections> = {};
                        selectedRequest.menuSelections.forEach((item) => {
                          const cat = item.category || "Other";
                          if (!grouped[cat]) grouped[cat] = [];
                          grouped[cat].push(item);
                        });
                        return Object.entries(grouped).map(([category, items]) => (
                          <div key={category}>
                            <p className="text-xs font-semibold text-muted-foreground mt-2">
                              {category}
                            </p>
                            <ul className="mt-1 space-y-0.5">
                              {items.map((item, i) => (
                                <li key={i} className="flex items-center justify-between">
                                  <span>{item.name}</span>
                                  {item.upcharge !== undefined && item.upcharge > 0 && (
                                    <span className="text-xs text-muted-foreground">
                                      +{formatCents(item.upcharge)}
                                    </span>
                                  )}
                                </li>
                              ))}
                            </ul>
                          </div>
                        ));
                      })()}
                    </>
                  )}
                </CardContent>
              </Card>

              {/* ─── Extras Card (Appetizers, Desserts, Beverages, Equipment) */}
              {(selectedRequest.appetizers ||
                selectedRequest.desserts ||
                selectedRequest.beverages ||
                selectedRequest.equipment) && (
                <Card>
                  <CardHeader className="pb-3">
                    <CardTitle className="text-base flex items-center gap-2">
                      <Star className="h-4 w-4" />
                      Extras
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4 text-sm">
                    {/* Appetizers */}
                    {selectedRequest.appetizers &&
                      selectedRequest.appetizers.selections &&
                      selectedRequest.appetizers.selections.length > 0 && (
                        <div>
                          <p className="font-medium mb-1">Appetizers</p>
                          {selectedRequest.appetizers.serviceStyle && (
                            <p className="text-xs text-muted-foreground mb-1">
                              Style: {selectedRequest.appetizers.serviceStyle}
                            </p>
                          )}
                          <div className="space-y-1">
                            {selectedRequest.appetizers.selections.map((item, i) => (
                              <div key={i} className="flex items-center justify-between text-sm">
                                <span>
                                  {item.itemName}
                                  <span className="text-muted-foreground text-xs ml-1">
                                    x{item.quantity}
                                  </span>
                                </span>
                                <span className="text-muted-foreground">
                                  {formatCents(item.subtotal)}
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                    {/* Desserts */}
                    {selectedRequest.desserts && selectedRequest.desserts.length > 0 && (
                      <div>
                        {selectedRequest.appetizers &&
                          selectedRequest.appetizers.selections?.length > 0 && <Separator />}
                        <p className="font-medium mb-1">Desserts</p>
                        <div className="space-y-1">
                          {selectedRequest.desserts.map((item, i) => (
                            <div key={i} className="flex items-center justify-between text-sm">
                              <span>
                                {item.itemName}
                                <span className="text-muted-foreground text-xs ml-1">
                                  x{item.quantity}
                                </span>
                              </span>
                              <span className="text-muted-foreground">
                                {formatCents(item.subtotal)}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Beverages */}
                    {selectedRequest.beverages && (
                      <div>
                        {((selectedRequest.appetizers &&
                          selectedRequest.appetizers.selections?.length > 0) ||
                          (selectedRequest.desserts && selectedRequest.desserts.length > 0)) && (
                          <Separator />
                        )}
                        <p className="font-medium mb-1">Beverages</p>
                        <div className="flex flex-wrap gap-2">
                          {selectedRequest.beverages.hasNonAlcoholic && (
                            <Badge variant="outline" className="text-xs">
                              Non-Alcoholic
                            </Badge>
                          )}
                          {selectedRequest.beverages.hasAlcoholic && (
                            <Badge variant="outline" className="text-xs">
                              <Wine className="h-3 w-3 mr-1" />
                              Alcoholic
                            </Badge>
                          )}
                          {selectedRequest.beverages.bartendingType && (
                            <Badge variant="outline" className="text-xs">
                              {selectedRequest.beverages.bartendingType}
                            </Badge>
                          )}
                          {selectedRequest.beverages.liquorQuality && (
                            <Badge variant="outline" className="text-xs">
                              {selectedRequest.beverages.liquorQuality}
                            </Badge>
                          )}
                        </div>
                      </div>
                    )}

                    {/* Equipment */}
                    {selectedRequest.equipment &&
                      selectedRequest.equipment.items &&
                      selectedRequest.equipment.items.length > 0 && (
                        <div>
                          <Separator />
                          <p className="font-medium mb-1">Equipment</p>
                          <div className="space-y-1">
                            {selectedRequest.equipment.items.map((item, i) => (
                              <div key={i} className="flex items-center justify-between text-sm">
                                <span>
                                  {item.item}
                                  <span className="text-muted-foreground text-xs ml-1">
                                    x{item.quantity}
                                  </span>
                                </span>
                                <span className="text-muted-foreground">
                                  {formatCents(item.subtotal)}
                                </span>
                              </div>
                            ))}
                          </div>
                          {selectedRequest.equipment.otherNotes && (
                            <p className="text-xs text-muted-foreground mt-1">
                              Note: {selectedRequest.equipment.otherNotes}
                            </p>
                          )}
                        </div>
                      )}
                  </CardContent>
                </Card>
              )}

              {/* ─── Dietary & Notes Card ────────────────────────────────── */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4" />
                    Dietary & Notes
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3 text-sm">
                  {selectedRequest.dietary?.restrictions &&
                    selectedRequest.dietary.restrictions.length > 0 && (
                      <div>
                        <p className="text-muted-foreground text-xs">Dietary Restrictions</p>
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {selectedRequest.dietary.restrictions.map((r, i) => (
                            <Badge key={i} variant="secondary" className="text-xs">
                              {r}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                  {selectedRequest.dietary?.allergies &&
                    selectedRequest.dietary.allergies.length > 0 && (
                      <div>
                        <p className="text-muted-foreground text-xs">Allergies</p>
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {selectedRequest.dietary.allergies.map((a, i) => (
                            <Badge key={i} variant="destructive" className="text-xs">
                              {a}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                  {selectedRequest.dietary?.specialNotes && (
                    <div>
                      <p className="text-muted-foreground text-xs">Dietary Notes</p>
                      <p className="mt-0.5">{selectedRequest.dietary.specialNotes}</p>
                    </div>
                  )}

                  {selectedRequest.specialRequests && (
                    <div>
                      <p className="text-muted-foreground text-xs">Special Requests</p>
                      <p className="mt-0.5">{selectedRequest.specialRequests}</p>
                    </div>
                  )}

                  <Separator />

                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <p className="text-muted-foreground text-xs">Internal Notes</p>
                      {notesMutation.isPending && (
                        <span className="text-xs text-muted-foreground flex items-center gap-1">
                          <Loader2 className="h-3 w-3 animate-spin" />
                          Saving...
                        </span>
                      )}
                    </div>
                    <Textarea
                      placeholder="Add internal notes about this quote request..."
                      value={internalNotesValue}
                      onChange={(e) => setInternalNotesValue(e.target.value)}
                      onBlur={handleNotesBlur}
                      rows={3}
                      className="resize-none"
                    />
                  </div>
                </CardContent>
              </Card>

              {/* ─── Pricing Summary Card ────────────────────────────────── */}
              <Card>
                <CardHeader className="pb-3">
                  <CardTitle className="text-base flex items-center gap-2">
                    <DollarSign className="h-4 w-4" />
                    Pricing Summary
                  </CardTitle>
                </CardHeader>
                <CardContent className="text-sm">
                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Per Person</span>
                      <span className="font-medium">
                        {formatCents(selectedRequest.estimatedPerPersonCents)}
                      </span>
                    </div>
                    <div className="flex items-center justify-between">
                      <span className="text-muted-foreground">Subtotal</span>
                      <span className="font-medium">
                        {formatCents(selectedRequest.estimatedSubtotalCents)}
                      </span>
                    </div>
                    {selectedRequest.discountPercent &&
                      parseFloat(selectedRequest.discountPercent) > 0 && (
                        <div className="flex items-center justify-between text-green-600">
                          <span>Discount ({selectedRequest.discountPercent}%)</span>
                          <span>Applied</span>
                        </div>
                      )}
                    <Separator />
                    <div className="flex items-center justify-between text-base">
                      <span className="font-semibold">Estimated Total</span>
                      <span className="font-bold text-lg">
                        {formatCents(selectedRequest.estimatedTotalCents)}
                      </span>
                    </div>
                  </div>

                  {/* Source info */}
                  {(selectedRequest.source || selectedRequest.decisionTimeline) && (
                    <>
                      <Separator className="my-3" />
                      <div className="grid grid-cols-2 gap-3">
                        {selectedRequest.source && (
                          <div>
                            <p className="text-muted-foreground text-xs">Source</p>
                            <p className="font-medium text-sm">{selectedRequest.source}</p>
                            {selectedRequest.referralDetail && (
                              <p className="text-xs text-muted-foreground">
                                {selectedRequest.referralDetail}
                              </p>
                            )}
                          </div>
                        )}
                        {selectedRequest.decisionTimeline && (
                          <div>
                            <p className="text-muted-foreground text-xs">Decision Timeline</p>
                            <p className="font-medium text-sm">
                              {selectedRequest.decisionTimeline}
                            </p>
                          </div>
                        )}
                      </div>
                    </>
                  )}
                </CardContent>
              </Card>

              {/* ─── Shopping List (aggregated ingredients) ────────────────── */}
              <ShoppingList quoteRequestId={selectedRequest.id} />
            </div>
          )}
        </div>
      </div>

      {/* ─── Convert Dialog ──────────────────────────────────────────────── */}
      <Dialog open={convertDialogOpen} onOpenChange={setConvertDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Convert Quote Request</DialogTitle>
            <DialogDescription>
              This will create a Client, Opportunity, and pre-filled Estimate from this quote
              request.
            </DialogDescription>
          </DialogHeader>

          {selectedRequest && (
            <div className="space-y-3 py-2">
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div>
                  <p className="text-muted-foreground text-xs">Contact</p>
                  <p className="font-medium">
                    {selectedRequest.firstName} {selectedRequest.lastName}
                  </p>
                </div>
                <div>
                  <p className="text-muted-foreground text-xs">Event Type</p>
                  <p className="font-medium">{selectedRequest.eventType}</p>
                </div>
                <div>
                  <p className="text-muted-foreground text-xs">Guest Count</p>
                  <p className="font-medium">{selectedRequest.guestCount}</p>
                </div>
                <div>
                  <p className="text-muted-foreground text-xs">Estimated Total</p>
                  <p className="font-medium text-lg">
                    {formatCents(selectedRequest.estimatedTotalCents)}
                  </p>
                </div>
              </div>
            </div>
          )}

          {convertMutation.isSuccess && convertedResult && (
            <div className="bg-green-50 border border-green-200 rounded-lg p-3 space-y-2">
              <p className="text-sm font-medium text-green-700 flex items-center gap-1.5">
                <Check className="h-4 w-4" />
                Conversion Successful
              </p>
              <div className="flex gap-2 flex-wrap">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setConvertDialogOpen(false);
                    navigate(`/opportunities/${convertedResult.opportunity.id}`);
                  }}
                >
                  <ExternalLink className="h-3.5 w-3.5 mr-1.5" />
                  View Opportunity
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setConvertDialogOpen(false);
                    navigate(`/estimates/${convertedResult.estimate.id}/view`);
                  }}
                >
                  <ExternalLink className="h-3.5 w-3.5 mr-1.5" />
                  View Estimate
                </Button>
              </div>
            </div>
          )}

          <DialogFooter>
            <Button variant="outline" onClick={() => setConvertDialogOpen(false)}>
              {convertMutation.isSuccess ? "Close" : "Cancel"}
            </Button>
            {!convertMutation.isSuccess && (
              <Button
                onClick={() => selectedRequest && convertMutation.mutate(selectedRequest.id)}
                disabled={convertMutation.isPending}
              >
                {convertMutation.isPending ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                    Converting...
                  </>
                ) : (
                  <>
                    <ArrowRight className="h-4 w-4 mr-1.5" />
                    Convert
                  </>
                )}
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ─── Disqualify Dialog ────────────────────────────────────────── */}
      <Dialog open={disqualifyDialogOpen} onOpenChange={setDisqualifyDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Disqualify this quote request</DialogTitle>
            <DialogDescription>
              Tell us why. This gets stored as the disqualification reason so we can learn
              what kinds of inbound aren't a fit (wrong date, out of area, budget mismatch,
              ghosted, spam, etc).
            </DialogDescription>
          </DialogHeader>
          <div className="py-2">
            <Textarea
              value={disqualifyReason}
              onChange={(e) => setDisqualifyReason(e.target.value)}
              placeholder="e.g. Date already booked; out of service area; budget too low; no response after 3 follow-ups"
              rows={4}
              autoFocus
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setDisqualifyDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={confirmDisqualify}>
              Disqualify
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
