import { OpenAI } from 'openai';
import { QuoteRequest, QuoteAiAnalysis } from '@shared/schema';

const openRouter = new OpenAI({
  apiKey: process.env.OPENROUTER_API_KEY || '',
  baseURL: 'https://openrouter.ai/api/v1',
  defaultHeaders: {
    'HTTP-Referer': 'https://catering-cms.replit.app',
    'X-Title': 'Home Bites Catering CMS'
  }
});

const DEEPSEEK_MODEL = 'deepseek/deepseek-chat-v3-0324:free';
const GEMINI_MODEL = 'google/gemini-2.0-flash-exp:free';
const CLAUDE_MODEL = 'anthropic/claude-3-haiku';

/**
 * Analyze a submitted quote request with AI.
 * Returns structured analysis for the sales team.
 */
export async function analyzeQuoteRequest(quote: QuoteRequest): Promise<QuoteAiAnalysis> {
  try {
    if (!process.env.OPENROUTER_API_KEY) {
      console.warn("OPENROUTER_API_KEY not set — skipping AI analysis");
      return { autoGeneratedNotes: "AI analysis unavailable — no API key configured." };
    }

    const prompt = buildQuoteAnalysisPrompt(quote);

    // Try model cascade: DeepSeek → Gemini → Claude
    for (const model of [DEEPSEEK_MODEL, GEMINI_MODEL, CLAUDE_MODEL]) {
      try {
        console.log(`Quote AI Analysis: Trying ${model} for quote #${quote.id}...`);
        const response = await openRouter.chat.completions.create({
          model,
          messages: [{ role: 'user', content: prompt }],
          max_tokens: 2000,
          temperature: 0.3,
          response_format: { type: "json_object" },
        });

        const content = response.choices[0]?.message?.content?.trim();
        if (!content) continue;

        const parsed = JSON.parse(content);
        console.log(`Quote AI Analysis: Successfully analyzed quote #${quote.id} with ${model}`);
        return {
          eventComplexityScore: clamp(parsed.eventComplexityScore, 1, 10),
          estimatedPrepHours: parsed.estimatedPrepHours ?? null,
          recommendedStaffCount: parsed.recommendedStaffCount ?? null,
          suggestedUpsells: Array.isArray(parsed.suggestedUpsells) ? parsed.suggestedUpsells.slice(0, 5) : [],
          suggestedAlternatives: Array.isArray(parsed.suggestedAlternatives) ? parsed.suggestedAlternatives.slice(0, 3) : [],
          pricingConfidence: clamp(parsed.pricingConfidence, 0, 1),
          marginEstimate: parsed.marginEstimate ?? null,
          autoGeneratedNotes: parsed.autoGeneratedNotes || null,
          analyzedAt: new Date().toISOString(),
        };
      } catch (err: any) {
        console.error(`Quote AI Analysis: ${model} failed:`, err.message);
        continue;
      }
    }

    // All models failed
    return { autoGeneratedNotes: "AI analysis failed — all models returned errors.", analyzedAt: new Date().toISOString() };
  } catch (error) {
    console.error("Quote AI Analysis: Fatal error:", error);
    return { autoGeneratedNotes: "AI analysis error.", analyzedAt: new Date().toISOString() };
  }
}

function clamp(val: any, min: number, max: number): number | undefined {
  if (val == null || isNaN(Number(val))) return undefined;
  return Math.max(min, Math.min(max, Number(val)));
}

function buildQuoteAnalysisPrompt(q: QuoteRequest): string {
  // Build a human-readable summary of the quote request
  const menuSelections = (q.menuSelections as any[]) || [];
  const appetizers = (q.appetizers as any)?.selections || [];
  const desserts = (q.desserts as any[]) || [];
  const beverages = q.beverages as any;
  const equipment = (q.equipment as any)?.items || [];
  const dietary = q.dietary as any;

  const sections = [
    `EVENT: ${q.eventType} on ${q.eventDate ? new Date(q.eventDate).toLocaleDateString() : 'TBD'}`,
    `GUESTS: ${q.guestCount}`,
    `VENUE: ${q.venueName || 'Not specified'}${q.venueHasKitchen ? ' (has kitchen)' : q.venueHasKitchen === false ? ' (no kitchen)' : ''}`,
    `SERVICE: ${q.serviceType || 'Not specified'} / ${q.serviceStyle || 'Not specified'}`,
    `MENU: Theme: ${q.menuTheme || 'Not selected'}, Tier: ${q.menuTier || 'Not selected'}`,
    menuSelections.length > 0 ? `MENU ITEMS: ${menuSelections.map(s => s.name).join(', ')}` : null,
    appetizers.length > 0 ? `APPETIZERS: ${appetizers.map((a: any) => `${a.itemName} x${a.quantity}`).join(', ')}` : null,
    desserts.length > 0 ? `DESSERTS: ${desserts.map((d: any) => `${d.itemName} x${d.quantity}`).join(', ')}` : null,
    beverages?.hasAlcoholic ? `BAR: ${beverages.bartendingType} hire, ${beverages.bartendingDurationHours || '?'}hrs, ${beverages.liquorQuality || 'standard'} quality` : null,
    beverages?.hasNonAlcoholic ? `NON-ALCOHOLIC: ${(beverages.nonAlcoholicSelections || []).join(', ')}` : null,
    equipment.length > 0 ? `EQUIPMENT: ${equipment.map((e: any) => `${e.item} x${e.quantity}`).join(', ')}` : null,
    dietary?.restrictions?.length ? `DIETARY: ${dietary.restrictions.join(', ')}` : null,
    dietary?.allergies?.length ? `ALLERGIES: ${dietary.allergies.join(', ')}` : null,
    q.hasCocktailHour ? `COCKTAIL HOUR: ${q.cocktailStartTime} - ${q.cocktailEndTime}` : null,
    q.hasMainMeal ? `MAIN MEAL: ${q.mainMealStartTime} - ${q.mainMealEndTime}` : null,
    q.hasCeremony ? `CEREMONY: ${q.ceremonyStartTime} - ${q.ceremonyEndTime}${q.ceremonySameSpace ? ' (same space as reception)' : ''}` : null,
    q.specialRequests ? `SPECIAL REQUESTS: ${q.specialRequests}` : null,
    `TIMING: Event ${q.eventStartTime || '?'} - ${q.eventEndTime || '?'}`,
  ].filter(Boolean).join('\n');

  return `You are an expert catering operations analyst for 'Home Bites Catering', a Seattle-based catering company.
Analyze this quote request and provide operational insights for the sales team.

HOME BITES CONTEXT:
- Based in Seattle, WA (1005 Terrace St). Travel fee applies for venues >10 miles.
- Kitchen: 1005 Terrace St, Seattle. Some venues have on-site kitchens.
- Team: Small operation, typically 1 chef + 2-4 staff for events.
- Menu themes: Taco Fiesta, American BBQ, Taste of Greece, Kebab Party, Taste of Italy, Vegan.
- Tiers: Bronze (basic), Silver, Gold, Diamond (premium). Bronze only for 50+ guests.
- Service fee: 15% standard, 20% full service.
- Minimum event value: $2,500. Deposit: 35%.
- Food cost target: 28-32% of revenue.

QUOTE REQUEST:
${sections}

Analyze this request and return ONLY a JSON object with these fields:
{
  "eventComplexityScore": <1-10 integer. 1=simple drop-off, 5=standard buffet wedding, 8=multi-service plated wedding, 10=complex multi-day event>,
  "estimatedPrepHours": <total kitchen prep hours needed, accounting for guest count and menu complexity>,
  "recommendedStaffCount": <total on-site staff recommended: chef(s) + servers + bartender(s)>,
  "suggestedUpsells": [
    {"item": "<specific upsell>", "reason": "<why this fits their event>", "estimatedValue": <dollar value>}
  ],
  "suggestedAlternatives": [
    {"original": "<something they picked>", "suggestion": "<better option>", "reason": "<why swap>"}
  ],
  "pricingConfidence": <0.0-1.0, how confident we are in the auto-calculated price being accurate>,
  "marginEstimate": <estimated food cost percentage, e.g. 30 means 30%>,
  "autoGeneratedNotes": "<2-4 sentence briefing for the sales team: key observations, potential issues, recommended approach for this client>"
}

Be specific to THIS event. Reference their actual selections. Flag anything unusual (e.g., very large party with budget tier, no kitchen at venue with complex menu, dietary constraints that conflict with menu choices).`;
}
