import { Inquiry, QuoteAiAnalysis } from '@shared/schema';
import { db } from '../db';
import { menus } from '@shared/schema';
import { eq } from 'drizzle-orm';
import { calculateMenuMargin, TierMarginAnalysis } from '../utils/menuMargin';
import { createChatCompletion, hasLlmProvider } from './llmClient';

/**
 * Analyze a submitted quote request with AI.
 * Returns structured analysis for the sales team.
 */
export async function analyzeInquiry(quote: Inquiry): Promise<QuoteAiAnalysis> {
  try {
    if (!hasLlmProvider()) {
      console.warn("No LLM provider configured — skipping AI analysis");
      return { autoGeneratedNotes: "AI analysis unavailable — no LLM provider configured." };
    }

    // Fetch real margin data for the selected menu/tier (Phase 3 — recipe-based costing)
    let tierMargin: TierMarginAnalysis | null = null;
    if (quote.menuTheme && quote.menuTier) {
      try {
        const [menu] = await db.select().from(menus).where(eq(menus.themeKey, quote.menuTheme));
        if (menu) {
          const allTiers = await calculateMenuMargin(menu.id);
          tierMargin = allTiers.find((t) => t.tierKey === quote.menuTier) || null;
        }
      } catch (err) {
        console.error("Failed to calculate tier margin for AI analysis:", err);
      }
    }

    const prompt = buildQuoteAnalysisPrompt(quote, tierMargin);

    try {
      console.log(`Quote AI Analysis: analyzing quote #${quote.id}...`);
      const { content, provider } = await createChatCompletion({
        messages: [{ role: 'user', content: prompt }],
        maxTokens: 2000,
        temperature: 0.3,
        json: true,
      });

      const parsed = JSON.parse(content);
      console.log(`Quote AI Analysis: successfully analyzed quote #${quote.id} via ${provider}`);
      return {
        eventComplexityScore: clamp(parsed.eventComplexityScore, 1, 10),
        estimatedPrepHours: parsed.estimatedPrepHours ?? null,
        recommendedStaffCount: parsed.recommendedStaffCount ?? null,
        suggestedUpsells: Array.isArray(parsed.suggestedUpsells) ? parsed.suggestedUpsells.slice(0, 5) : [],
        suggestedAlternatives: Array.isArray(parsed.suggestedAlternatives) ? parsed.suggestedAlternatives.slice(0, 3) : [],
        pricingConfidence: clamp(parsed.pricingConfidence, 0, 1),
        marginQuote: parsed.marginQuote ?? null,
        autoGeneratedNotes: parsed.autoGeneratedNotes || null,
        analyzedAt: new Date().toISOString(),
      };
    } catch (err: any) {
      console.error("Quote AI Analysis: providers failed:", err?.message);
      return {
        autoGeneratedNotes: "AI analysis failed — providers returned errors.",
        analyzedAt: new Date().toISOString(),
      };
    }
  } catch (error) {
    console.error("Quote AI Analysis: Fatal error:", error);
    return { autoGeneratedNotes: "AI analysis error.", analyzedAt: new Date().toISOString() };
  }
}

function clamp(val: any, min: number, max: number): number | undefined {
  if (val == null || isNaN(Number(val))) return undefined;
  return Math.max(min, Math.min(max, Number(val)));
}

function buildQuoteAnalysisPrompt(q: Inquiry, tierMargin: TierMarginAnalysis | null = null): string {
  // Build a human-readable summary of the quote request
  const menuSelections = (q.menuSelections as any[]) || [];
  const appetizers = (q.appetizers as any)?.selections || [];
  const desserts = (q.desserts as any[]) || [];
  const beverages = q.beverages as any;
  const equipment = (q.equipment as any)?.items || [];
  const dietary = q.dietary as any;

  const sections = [
    `EVENT: ${q.eventType} on ${q.eventDate ? new Date(q.eventDate).toLocaleDateString() : 'TBD'}`,
    `GUESTS: ${q.guestCount}`,
    `VENUE: ${q.venueName || 'Not specified'}${q.venueHasKitchen ? ' (has kitchen)' : q.venueHasKitchen === false ? ' (no kitchen)' : ''}`,
    `SERVICE: ${q.serviceType || 'Not specified'} / ${q.serviceStyle || 'Not specified'}`,
    `MENU: Theme: ${q.menuTheme || 'Not selected'}, Tier: ${q.menuTier || 'Not selected'}`,
    menuSelections.length > 0 ? `MENU ITEMS: ${menuSelections.map(s => s.name).join(', ')}` : null,
    appetizers.length > 0 ? `APPETIZERS: ${appetizers.map((a: any) => `${a.itemName} x${a.quantity}`).join(', ')}` : null,
    desserts.length > 0 ? `DESSERTS: ${desserts.map((d: any) => `${d.itemName} x${d.quantity}`).join(', ')}` : null,
    beverages?.hasAlcoholic ? `BAR: ${beverages.bartendingType} hire, ${beverages.bartendingDurationHours || '?'}hrs, ${beverages.liquorQuality || 'standard'} quality` : null,
    beverages?.hasNonAlcoholic ? `NON-ALCOHOLIC: ${(beverages.nonAlcoholicSelections || []).join(', ')}` : null,
    equipment.length > 0 ? `EQUIPMENT: ${equipment.map((e: any) => `${e.item} x${e.quantity}`).join(', ')}` : null,
    dietary?.restrictions?.length ? `DIETARY: ${dietary.restrictions.join(', ')}` : null,
    dietary?.allergies?.length ? `ALLERGIES: ${dietary.allergies.join(', ')}` : null,
    q.hasCocktailHour ? `COCKTAIL HOUR: ${q.cocktailStartTime} - ${q.cocktailEndTime}` : null,
    q.hasMainMeal ? `MAIN MEAL: ${q.mainMealStartTime} - ${q.mainMealEndTime}` : null,
    q.hasCeremony ? `CEREMONY: ${q.ceremonyStartTime} - ${q.ceremonyEndTime}${q.ceremonySameSpace ? ' (same space as reception)' : ''}` : null,
    q.specialRequests ? `SPECIAL REQUESTS: ${q.specialRequests}` : null,
    `TIMING: Event ${q.eventStartTime || '?'} - ${q.eventEndTime || '?'}`,
  ].filter(Boolean).join('\n');

  return `You are an expert catering operations analyst for 'Home Bites Catering', a Seattle-based catering company.
Analyze this quote request and provide operational insights for the sales team.

HOME BITES CONTEXT:
- Based in Seattle, WA (1005 Terrace St). Travel fee applies for venues >10 miles.
- Kitchen: 1005 Terrace St, Seattle. Some venues have on-site kitchens.
- Team: Small operation, typically 1 chef + 2-4 staff for events.
- Menu themes: Taco Fiesta, American BBQ, Taste of Greece, Kebab Party, Taste of Italy, Vegan.
- Tiers: Bronze (basic), Silver, Gold, Diamond (premium). Bronze only for 50+ guests.
- Service fee: 15% standard, 20% full service.
- Minimum event value: $2,500. Deposit: 35%.
- Food cost target: 28-32% of revenue.

${tierMargin ? `REAL COST DATA FOR THIS QUOTE'S SELECTED TIER (from database):
- Tier: ${tierMargin.tierName}
- Price/person: $${(tierMargin.pricePerPersonCents / 100).toFixed(2)}
- Estimated food cost/person: $${(tierMargin.estimatedFoodCostCents / 100).toFixed(2)}
- Food cost %: ${tierMargin.foodCostPercent.toFixed(1)}% (status: ${tierMargin.status})
- Margin/person: $${(tierMargin.marginPerPersonCents / 100).toFixed(2)}
- Linked recipes: ${tierMargin.linkedItemCount}, Unlinked items: ${tierMargin.unlinkedItemCount}
Use this real cost data for your marginQuote and pricingConfidence fields.

` : ''}QUOTE REQUEST:
${sections}

Analyze this request and return ONLY a JSON object with these fields:
{
  "eventComplexityScore": <1-10 integer. 1=simple drop-off, 5=standard buffet wedding, 8=multi-service plated wedding, 10=complex multi-day event>,
  "estimatedPrepHours": <total kitchen prep hours needed, accounting for guest count and menu complexity>,
  "recommendedStaffCount": <total on-site staff recommended: chef(s) + servers + bartender(s)>,
  "suggestedUpsells": [
    {"item": "<specific upsell>", "reason": "<why this fits their event>", "estimatedValue": <dollar value>}
  ],
  "suggestedAlternatives": [
    {"original": "<something they picked>", "suggestion": "<better option>", "reason": "<why swap>"}
  ],
  "pricingConfidence": <0.0-1.0, how confident we are in the auto-calculated price being accurate>,
  "marginQuote": <estimated food cost percentage, e.g. 30 means 30%>,
  "autoGeneratedNotes": "<2-4 sentence briefing for the sales team: key observations, potential issues, recommended approach for this client>"
}

Be specific to THIS event. Reference their actual selections. Flag anything unusual (e.g., very large party with budget tier, no kitchen at venue with complex menu, dietary constraints that conflict with menu choices).`;
}
