import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { ColumnDef } from "@tanstack/react-table";
import { Link } from "wouter";
import { DataTable } from "@/components/ui/data-table";
import BadgeStatus from "@/components/ui/badge-status";
import { Button } from "@/components/ui/button";
import { Estimate } from "@shared/schema";
import { formatDate, formatCurrency } from "@/lib/utils";
import { EyeIcon, PenIcon, PlusIcon, TrashIcon, SendIcon } from "lucide-react";
import { useCanWrite, useCanViewFinancials } from "@/hooks/usePermissions";
import { 
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";

export default function EstimateList() {
  const canWrite = useCanWrite();
  const canViewFinancials = useCanViewFinancials();
  const { data: estimates = [], isLoading } = useQuery<Estimate[]>({
    queryKey: ["/api/estimates"],
  });

  const { data: clients = [] } = useQuery<any[]>({
    queryKey: ["/api/clients"],
  });

  const [estimateToDelete, setEstimateToDelete] = useState<Estimate | null>(null);
  const [estimateToSend, setEstimateToSend] = useState<Estimate | null>(null);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Helper to get client name from ID
  const getClientName = (clientId: number) => {
    const client = clients.find((c: any) => c.id === clientId);
    return client ? `${client.firstName} ${client.lastName}` : "Unknown Client";
  };

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      await apiRequest("DELETE", `/api/estimates/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/estimates"] });
      toast({
        title: "Quote deleted",
        description: "The quote has been deleted successfully."
      });
      setEstimateToDelete(null);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: `Failed to delete quote: ${error.message}`,
        variant: "destructive",
      });
    },
  });

  // Send estimate mutation
  const sendMutation = useMutation({
    mutationFn: async (id: number) => {
      await apiRequest("PATCH", `/api/estimates/${id}`, {
        status: "sent",
        sentAt: new Date()
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/estimates"] });
      toast({
        title: "Quote sent",
        description: "The quote has been sent to the client."
      });
      setEstimateToSend(null);
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: `Failed to send estimate: ${error.message}`,
        variant: "destructive",
      });
    },
  });

  const handleDelete = () => {
    if (estimateToDelete) {
      deleteMutation.mutate(estimateToDelete.id);
    }
  };

  const handleSend = () => {
    if (estimateToSend) {
      sendMutation.mutate(estimateToSend.id);
    }
  };

  const columns: ColumnDef<Estimate>[] = useMemo(() => {
    const baseColumns: ColumnDef<Estimate>[] = [
      {
        accessorKey: "client",
        header: "Client",
        cell: ({ row }) => (
          <span className="font-medium text-neutral-900">
            {getClientName(row.original.clientId)}
          </span>
        ),
      },
      {
        accessorKey: "eventType",
        header: "Event Type",
        cell: ({ row }) => <span>{row.original.eventType}</span>,
      },
      {
        accessorKey: "eventDate",
        header: "Event Date",
        cell: ({ row }) => (
          <span>
            {row.original.eventDate
              ? formatDate(new Date(row.original.eventDate))
              : "—"}
          </span>
        ),
      },
    ];

    // Conditionally add Amount column for admins
    if (canViewFinancials) {
      baseColumns.push({
        accessorKey: "total",
        header: "Amount",
        cell: ({ row }) => (
          <span className="font-medium">{formatCurrency(row.original.total / 100)}</span>
        ),
      });
    }

    // Add Status and Actions columns
    baseColumns.push(
      {
        accessorKey: "status",
        header: "Status",
        cell: ({ row }) => {
          const raw = row.original.status;
          const derived =
            raw === "sent" && (row.original as any).viewedAt ? "viewed" : raw;
          const isAutoGenerated = (row.original as any).autoGenerated;
          return (
            <div className="flex items-center gap-1.5">
              <BadgeStatus status={derived} />
              {isAutoGenerated && (
                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-purple-100 text-purple-700" title="Auto-generated draft — review before sending">
                  Auto
                </span>
              )}
            </div>
          );
        },
      },
      {
        id: "actions",
        header: "Actions",
        cell: ({ row }) => {
          const isEditable = row.original.status === "draft" && canWrite;
          const isSendable = row.original.status === "draft" && canWrite;

          return (
            <div className="flex items-center space-x-2">
              <Link to={`/estimates/${row.original.id}/view`}>
                <div className="text-primary-purple hover:text-primary-blue transition cursor-pointer">
                  <EyeIcon className="h-4 w-4" />
                </div>
              </Link>

              {isEditable && (
                <Link to={`/estimates/${row.original.id}/edit`}>
                  <div className="text-primary-purple hover:text-primary-blue transition cursor-pointer">
                    <PenIcon className="h-4 w-4" />
                  </div>
                </Link>
              )}

              {isSendable && (
                <button
                  className="text-primary-purple hover:text-primary-blue transition"
                  onClick={() => setEstimateToSend(row.original)}
                >
                  <SendIcon className="h-4 w-4" />
                </button>
              )}

              {isEditable && (
                <button
                  className="text-red-500 hover:text-red-700 transition"
                  onClick={() => setEstimateToDelete(row.original)}
                >
                  <TrashIcon className="h-4 w-4" />
                </button>
              )}
            </div>
          );
        },
      }
    );

    return baseColumns;
  }, [canWrite, canViewFinancials, clients]);

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h1 className="font-poppins text-2xl font-bold text-neutral-900">Quotes</h1>
        {canWrite && (
          <Link href="/estimates/new">
            <Button className="bg-gradient-to-r from-[#8A2BE2] to-[#4169E1] hover:opacity-90">
              <PlusIcon className="mr-1 h-4 w-4" />
              New Quote
            </Button>
          </Link>
        )}
      </div>

      <DataTable 
        columns={columns} 
        data={estimates} 
        searchKey="client"
        loading={isLoading}
        emptyMessage="No quotes found. Create your first quote to get started."
      />

      <AlertDialog open={!!estimateToDelete}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete this quote. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setEstimateToDelete(null)}>Cancel</AlertDialogCancel>
            <AlertDialogAction 
              onClick={handleDelete}
              className="bg-red-500 hover:bg-red-600"
            >
              {deleteMutation.isPending ? "Deleting..." : "Delete"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <AlertDialog open={!!estimateToSend}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Send Quote</AlertDialogTitle>
            <AlertDialogDescription>
              This will send the quote to the client. The status will be changed to "Sent".
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setEstimateToSend(null)}>Cancel</AlertDialogCancel>
            <AlertDialogAction 
              onClick={handleSend}
              className="bg-gradient-to-r from-[#8A2BE2] to-[#4169E1] hover:opacity-90"
            >
              {sendMutation.isPending ? "Sending..." : "Send Quote"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
